### ISSUE TITLE
Error creating site - 

### ISSUE THREAD

**Issue by raf-rodrigues** [WordOps/WordOps#11]
I used the command to create a site with wpredis and this error appeared.

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 982, in emit
    stream.write(msg)
UnicodeEncodeError: 'latin-1' codec can't encode character '\ufffd' in position 366: ordinal not in range(256)
Call stack:
  File "/usr/local/bin/wo", line 9, in <module>
    load_entry_point('wo==3.9.1', 'console_scripts', 'wo')()
  File "/usr/local/lib/python3.5/dist-packages/wo-3.9.1-py3.5.egg/wo/cli/main.py", line 100, in main
    app.run()
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/core/foundation.py", line 694, in run
    self.controller._dispatch()
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/core/controller.py", line 455, in _dispatch
    return func()
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/core/controller.py", line 455, in _dispatch
    return func()
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/core/controller.py", line 461, in _dispatch
    return func()
  File "/usr/local/lib/python3.5/dist-packages/wo-3.9.1-py3.5.egg/wo/cli/plugins/site.py", line 522, in default
    wo_auth = site_package_check(self, stype)
  File "/usr/local/lib/python3.5/dist-packages/wo-3.9.1-py3.5.egg/wo/cli/plugins/site_functions.py", line 903, in site_package_check
    disp_msg=False))
  File "/usr/local/lib/python3.5/dist-packages/wo-3.9.1-py3.5.egg/wo/cli/plugins/stack.py", line 1547, in install
    self.pre_pref(apt_packages)
  File "/usr/local/lib/python3.5/dist-packages/wo-3.9.1-py3.5.egg/wo/cli/plugins/stack.py", line 160, in pre_pref
    WORepo.add(self, ppa=WOVariables.wo_php_repo)
  File "/usr/local/lib/python3.5/dist-packages/wo-3.9.1-py3.5.egg/wo/core/apt_repo.py", line 51, in add
    .format(ppa_name=ppa))
  File "/usr/local/lib/python3.5/dist-packages/wo-3.9.1-py3.5.egg/wo/core/shellexec.py", line 33, in cmd_exec
    .format(cmd_stdout, cmd_stderr))
  File "/usr/local/lib/python3.5/dist-packages/wo-3.9.1-py3.5.egg/wo/core/logging.py", line 47, in debug
    self.app.log.debug(Log.HEADER + msg + Log.ENDC)
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/ext/ext_logging.py", line 307, in debug
    self.backend.debug(msg, **kwargs)
Message: '\x1b[95mCommand Output: OK\n, \nCommand Error: gpg: keyring `/tmp/tmp6r_1wldt/secring.gpg\' created\ngpg: keyring `/tmp/tmp6r_1wldt/pubring.gpg\' created\ngpg: requesting key E5267A6C from hkp server keyserver.ubuntu.com\ngpg: /tmp/tmp6r_1wldt/trustdb.gpg: trustdb created\ngpg: key E5267A6C: public key "Launchpad PPA for Ond\\xc5\\x99ej Sur\ufffd" imported\ngpg: Total number processed: 1\ngpg:               imported: 1  (RSA: 1)\n\x1b[0m'

```

**Comment by wolerine** [comment]
https://askubuntu.com/a/393649
Check this post

**Comment by jeroenops** [comment]
Thank you for this issue. As @wolerine correctly stated, this can be resolved easily. I am hesitant to change / set the locale, because that might produce other problems. Most VPS providers roll out a default config, so this shouldn't occur much.
