### ISSUE TITLE
Can't install or update

### ISSUE THREAD

**Issue by andremacola** [WordOps/WordOps#163]
wo update or wget -qO wo wops.cc && sudo bash wo

Now `wo` command is broken on my server (Ubuntu 18.04)

Already tried to remove `sudo rm /usr/local/bin/wo` and reinstall but it gives me `command not found: wo`

```
E: Failed to fetch http://download.opensuse.org/repositories/home:/virtubox:/WordOps/xUbuntu_18.04/InRelease  403  Forbidden [IP: 2620:113:80c0:8::13 80]
E: The repository 'http://download.opensuse.org/repositories/home:/virtubox:/WordOps/xUbuntu_18.04  InRelease' is no longer signed.
```

```
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wo==3.9.8.11' distribution was not found and is required by the application
```

**Comment by andremacola** [comment]
Fixed deleting the `wo-repo.list wo-repo.list.save wordops-ubuntu-nginx-wo-bionic.list wordops-ubuntu-nginx-wo-bionic.list.save` files inside `/etc/apt/sources.list.d` and running the install command again.
