### ISSUE TITLE
wo secure doesn't work with WO v3.11.3

### ISSUE THREAD

**Issue by mdotk** [WordOps/WordOps#243]
Seems to be related to this issue https://github.com/WordOps/WordOps/issues/239

```
root@xxxx:~# wo secure --port 27156
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/wo/cli/main.py", line 102, in main
    app.run()
  File "/usr/local/lib/python3.6/dist-packages/cement/core/foundation.py", line 882, in run
    return_val = self.controller._dispatch()
  File "/usr/local/lib/python3.6/dist-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/usr/local/lib/python3.6/dist-packages/cement/core/controller.py", line 477, in _dispatch
    return func()
  File "/usr/local/lib/python3.6/dist-packages/wo/cli/plugins/secure.py", line 58, in default
    self.secure_port()
  File "/usr/local/lib/python3.6/dist-packages/wo/cli/plugins/secure.py", line 120, in secure_port
    data = dict(release=WOVar.wo_version, port=port)
UnboundLocalError: local variable 'port' referenced before assignment
```

**Comment by VirtuBox** [comment]
Hello @mdotk, 
thanks for your report, I will take a look on this.

**Comment by sheck87** [comment]
Also same problem with letsencrypt 😢

**Comment by VirtuBox** [comment]
Issue has been fixed in the last release.

Please update WordOps with the command `wo update`.
