### ISSUE TITLE
PHP FastCGI sockets mismatch

### ISSUE THREAD

**Issue by Slapbox** [WordOps/WordOps#256]
WordOps looks for sockets that don't exist, I'm guessing due to a discrepancy between how WordOps and EasyEngine refer to PHP versions. EasyEngine uses `php7.2` to define php7.2 and WordOps uses `php72`

We upgraded from EasyEngine 3,x,

**Socket issue 1:**

So,  WordOps is configured to look for `php72-fpm.sock` but what actually exists is `php7.2-fpm.sock`. Same goes for php7.4. This is fixed by symlinking to the correct name, but this is destroyed on reboot.

Is there somewhere I can change the name of the socket that won't be destroyed when upgrading WordOps? Or is there some other way we can get this fixed besides tacking on a startup script to create symlinks?

**Socket issue 2:**

What's the purpose of this socket? This one is also broken, and there's nothing I can symlink that I see. I don't understand the purpose of this socket, but its absence doesn't seem to cause any negative effects, which confuses me even more.

`unix:/var/run/php/php72-two-fpm.sock`

----

Really loving WordOps besides this hiccup! Here's the system info:

### System Information

- [x] `lsb_release -a`
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.12 (stretch)
Release:        9.12
Codename:       stretch
```

- [x] `wo info`

```

NGINX (1.16.1 ):

user                             www-data
worker_processes                 auto
worker_connections               50000
keepalive_timeout                8
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/wo/cli/main.py", line 102, in mai                                                                                                                          n
    app.run()
  File "/usr/local/lib/python3.5/dist-packages/cement/core/foundation.py", line                                                                                                                           882, in run
    return_val = self.controller._dispatch()
  File "/usr/local/lib/python3.5/dist-packages/cement/core/controller.py", line                                                                                                                           471, in _dispatch
    return func()
  File "/usr/local/lib/python3.5/dist-packages/cement/core/controller.py", line                                                                                                                           477, in _dispatch
    return func()
  File "/usr/local/lib/python3.5/dist-packages/wo/cli/plugins/info.py", line 389                                                                                                                          , in default
    self.info_php()
  File "/usr/local/lib/python3.5/dist-packages/wo/cli/plugins/info.py", line 95,                                                                                                                           in info_php
    www_ping_path = wconfig['ping.path']
  File "/usr/lib/python3.5/configparser.py", line 1230, in __getitem__
    raise KeyError(key)
KeyError: 'ping.path'
```

Not sure what this error is. Everything seems to work.

- [x] `nginx -V`

```
nginx version: nginx/1.16.1 (WordOps Nginx-wo)
built with OpenSSL 1.1.1d  10 Sep 2019
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/usr/src/packages/BUILD=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-z,relro -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo' --with-debug --with-pcre-jit --with-file-aio --with-threads --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-http_realip_module --with-http_v2_hpack_enc --with-http_auth_request_module --with-openssl-opt='enable-ec_nistp_64_gcc_128 enable-tls1_3 no-ssl3-method' --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_sub_module --without-http_memcached_module --add-module=/usr/src/packages/BUILD/debian/modules/headers-more-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/nginx-auth-pam --add-module=/usr/src/packages/BUILD/debian/modules/nginx-cache-purge --add-module=/usr/src/packages/BUILD/debian/modules/nginx-echo --add-module=/usr/src/packages/BUILD/debian/modules/nginx-upstream-fair --add-module=/usr/src/packages/BUILD/debian/modules/ngx_http_substitutions_filter_module --add-module=/usr/src/packages/BUILD/debian/modules/memc-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/srcache-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/HttpRedisModule --add-module=/usr/src/packages/BUILD/debian/modules/redis2-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/ngx_devel_kit --add-module=/usr/src/packages/BUILD/debian/modules/set-misc-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/nginx-module-vts --add-module=/usr/src/packages/BUILD/debian/modules/ngx_brotli

```

- [x] `wo -v`

```
WordOps v3.11.4
Copyright (c) 2019 WordOps.
```

- [x] `wp cli info --allow-root`

```

OS:     Linux 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php7.4
PHP version:    7.4.3
php.ini used:   /etc/php/7.4/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /run/php
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.4.0
```

**Comment by Slapbox** [comment]
Easier and more persistent (until next WO upgrade) - update the `/etc/nginx/conf.d/upstream.conf` which contains the socket names which will be used. Modify them to match what's actually created in `/var/run/php`

**Comment by Slapbox** [comment]
Running `wo stack upgrade` fixed all of this. Whoops...
