### ISSUE TITLE
configparser.NoSectionError: No section: 'letsencrypt'

### ISSUE THREAD

**Issue by w33zy** [WordOps/WordOps#276]
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

```
NGINX (1.16.1 ):

user                             www-data
worker_processes                 auto
worker_connections               50000
keepalive_timeout                8
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1

PHP (7.2.29-1):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php72-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9172

PHP (7.3.16-1):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php73-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9173

PHP (7.4.4):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php74-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9174

MySQL (10.3.22-MariaDB) on localhost:

port                             3306
wait_timeout                     60
interactive_timeout              28800
max_used_connections             21
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf
```

```
nginx version: nginx/1.16.1 (WordOps Nginx-wo)
built with OpenSSL 1.1.1d  10 Sep 2019
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-xSli4x/nginx-1.16.1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo' --with-debug --with-pcre-jit --with-file-aio --with-threads --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-http_realip_module --with-http_v2_hpack_enc --with-http_auth_request_module --with-openssl-opt='enable-ec_nistp_64_gcc_128 enable-tls1_3 no-ssl3-method' --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_sub_module --without-http_memcached_module --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/headers-more-nginx-module --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/nginx-auth-pam --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/nginx-cache-purge --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/nginx-echo --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/nginx-upstream-fair --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/ngx_http_substitutions_filter_module --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/memc-nginx-module --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/srcache-nginx-module --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/HttpRedisModule --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/redis2-nginx-module --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/ngx_devel_kit --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/set-misc-nginx-module --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/nginx-module-vts --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/ngx_brotli
```

`WordOps v3.11.4`

```
OS:     Linux 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php7.4
PHP version:    7.4.4
php.ini used:   /etc/php/7.4/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /root
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.4.0
```

`https://transfer.vtbox.net/WA3nR/wordops.txt`

Hello guys,

I am having an issue with trying to install a LE certification on a subdomain.
Here is the response I get...

```
root@hxxxx:~# wo site update store.xxxxxx.com --le
Traceback (most recent call last):
  File "/usr/lib/python3.6/configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'letsencrypt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/wo/cli/main.py", line 102, in main
    app.run()
  File "/usr/local/lib/python3.6/dist-packages/cement/core/foundation.py", line 882, in run
    return_val = self.controller._dispatch()
  File "/usr/local/lib/python3.6/dist-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/usr/local/lib/python3.6/dist-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/usr/local/lib/python3.6/dist-packages/cement/core/controller.py", line 477, in _dispatch
    return func()
  File "/usr/local/lib/python3.6/dist-packages/wo/cli/plugins/site_update.py", line 138, in default
    self.doupdatesite(pargs)
  File "/usr/local/lib/python3.6/dist-packages/wo/cli/plugins/site_update.py", line 450, in doupdatesite
    'keylength')
  File "/usr/lib/python3.6/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.6/configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'letsencrypt'
```

**Comment by vikas5914** [comment]
dup of https://github.com/WordOps/WordOps/issues/264 

You can  open the `/etc/wo/wo.conf` file and add the missing [letsencrypt] block.

```
[letsencrypt]

keylength = "ec-384"
```

**Comment by w33zy** [comment]
So I'll take it that this hasn't be fixed officially yet, so an update will erase this fix.

**Comment by vikas5914** [comment]
@w33zy The update will not erase this fix because it does not update the wo.conf file. which is the root cause of this issue.

**Comment by VirtuBox** [comment]
Hello @w33zy @vikas5914, 
thanks for your report, a fix will be available in the next release.
