### ISSUE TITLE
Error on installing Admin Stack

### ISSUE THREAD

**Issue by majiix** [WordOps/WordOps#293]
The command bellow generates the following error:

` wo stack install --admin`

```
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/wo/cli/main.py", line 102, in main
    app.run()
  File "/usr/local/lib/python3.6/dist-packages/cement/core/foundation.py", line 882, in run
    return_val = self.controller._dispatch()
  File "/usr/local/lib/python3.6/dist-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/usr/local/lib/python3.6/dist-packages/cement/core/controller.py", line 477, in _dispatch
    return func()
  File "/usr/local/lib/python3.6/dist-packages/wo/cli/plugins/stack.py", line 537, in install
    post_pref(self, [], packages)
  File "/usr/local/lib/python3.6/dist-packages/wo/cli/plugins/stack_pref.py", line 1420, in post_pref
    .format(wo_netdata),
UnboundLocalError: local variable 'wo_netdata' referenced before assignment
```

**Comment by majiix** [comment]
Any update on this?

**Comment by majiix** [comment]
Any update on this @VirtuBox ?

**Comment by mohammad-chavoshipor** [comment]
@VirtuBox 
Me too,
I have a problem when running the command 
`
wo stack install
`
