### ISSUE TITLE
[Urgent] New PHP 8.0 will fail the installation

### ISSUE THREAD

**Issue by tdtgit** [WordOps/WordOps#318]
# Issue

The new PHP 8.0rc1 package will automatically install on Ubuntu 20.04 and will fail:

1. The WordPress installation
```^[[32m2020-10-11 16:32:48,520 (INFO) wo : ^[[94mDownloading WordPress           ^[[0m
^[[36m2020-10-11 16:32:48,520 (DEBUG) wo.core.logging : ^[[95mChanging directory to /var/www/test.com/htdocs/^[[0m
^[[36m2020-10-11 16:32:48,520 (DEBUG) wo.core.logging : ^[[95mRunning command: wp --allow-root core download^[[0m
^[[36m2020-10-11 16:32:49,070 (DEBUG) wo.core.logging : ^[[95mCommand Output: ,
Command Error: PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php:195
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php(195): implode()
#1 phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests.php(379): Requests_Transport_fsockopen->request()
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/utils.php(681): Requests::request()
#3 phar:///usr/local/bin/wp/vendor/wp-cli/core-command/src/Core_Command.php(310): WP_CLI\Utils\http_request()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/core-command/src/Core_Command.php(319): Core_Command::read()
#5 phar:///usr/local/bin/wp/vendor/wp-cli/core-command/src/Core_Command.php(183): Core_Command->get_download_offer()
#6 [internal function]: Core_Command->download()
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(98): call_user_func()
#8 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}()
#9 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(451): call_user_func()
#10 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(371): WP_CLI\Dispatcher\Subcommand->invoke()
#11 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(394): WP_CLI\Runner->run_command()
#12 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(87): WP_CLI\Runner->run_command_and_exit()
#13 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1102): WP_CLI\Runner->do_early_invoke()
#14 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#15 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\LaunchRunner->process()
#16 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#17 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('...')
#18 /usr/local/bin/wp(4): include('...')
#19 {main}
  thrown in phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php on line 195
^[[0m
^[[32m2020-10-11 16:32:49,071 (INFO) wo : ^[[94m[^[[0m^[[91mFail^[[94m]^[[0m
^[[36m2020-10-11 16:32:49,071 (DEBUG) wo.core.logging : ^[[95m'download WordPress core failed'^[[0m
^[[32m2020-10-11 16:32:49,071 (INFO) wo : ^[[94m^[[91mThere was a serious error encountered...^[[0m
^[[32m2020-10-11 16:32:49,071 (INFO) wo : ^[[94m^[[91mCleaning up afterwards...^[[0m
```
2. CLI as PHP 8.0rc1 become default version:
```root@vultr:~# php -v
PHP 8.0.0rc1 (cli) (built: Oct 11 2020 14:02:16) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.0rc1, Copyright (c), by Zend Technologies
```

# Workaround
1. Not yet
2. Current user: do not run `apt upgrade` right now. If you accidentally upgrade and download the PHP 8.0 package, run ```sudo update-alternatives --config php``` then select your defalt PHP-CLI version.

**Comment by VirtuBox** [comment]
Hello @tdtgit,

thanks for your report, I'm going to publish a fix tomorrow for this issue.

**Comment by mkvtvseries** [comment]
Hello, How to access/see monitoring (NETDATA)?
I didn't see any guide, Kindly please

**Comment by VirtuBox** [comment]
> Hello, How to access/see monitoring (NETDATA)?
> I didn't see any guide, Kindly please

https://docs.wordops.net/getting-started/post-install-steps/#wordops-backend

**Comment by mkvtvseries** [comment]
> > Hello, How to access/see monitoring (NETDATA)?
> > I didn't see any guide, Kindly please
> 
> https://docs.wordops.net/getting-started/post-install-steps/#wordops-backend

THANK YOU

**Comment by VirtuBox** [comment]
Issue has been fixed in the last release.
