### ISSUE TITLE
Issues running wo

### ISSUE THREAD

**Issue by ajaydsouza** [WordOps/WordOps#334]
```
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/opt/wo/lib/python3.6/site-packages/wo/cli/main.py", line 93, in main
    with app:
  File "/opt/wo/lib/python3.6/site-packages/cement/core/foundation.py", line 1501, in __enter__
    self.setup()
  File "/opt/wo/lib/python3.6/site-packages/cement/core/foundation.py", line 852, in setup
    self._setup_plugin_handler()
  File "/opt/wo/lib/python3.6/site-packages/cement/core/foundation.py", line 1339, in _setup_plugin_handler
    self.plugin.load_plugins(self.plugin.get_enabled_plugins())
  File "/opt/wo/lib/python3.6/site-packages/cement/ext/ext_plugin.py", line 290, in load_plugins
    self.load_plugin(plugin_name)
  File "/opt/wo/lib/python3.6/site-packages/cement/ext/ext_plugin.py", line 259, in load_plugin
    if self._load_plugin_from_bootstrap(plugin_name, self.bootstrap):
  File "/opt/wo/lib/python3.6/site-packages/cement/ext/ext_plugin.py", line 225, in _load_plugin_from_bootstrap
    __import__(full_module, globals(), locals(), [], 0)
  File "/opt/wo/lib/python3.6/site-packages/wo/cli/plugins/clean.py", line 8, in <module>
    from wo.core.aptget import WOAptGet
  File "/opt/wo/lib/python3.6/site-packages/wo/core/aptget.py", line 8, in <module>
    import apt
ModuleNotFoundError: No module named 'apt'

```

I'm getting the above error since the upgrade to the latest version of wordops.

System Information

- [ ] `lsb_release -a`
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

- [ ] `wo info`
Cannot run due to the above error

- [ ] `nginx -V`
nginx version: nginx/1.18.0 (WordOps Nginx-wo)
built with OpenSSL 1.1.1g  21 Apr 2020
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-W7QLqg/nginx-1.18.0=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -flto -ffat-lto-objects -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -fPIC -flto -ffat-lto-objects' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo' --with-debug --with-pcre-jit --with-file-aio --with-threads --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-openssl-opt='zlib enable-ec_nistp_64_gcc_128 enable-tls1_3 no-ssl3-method -fPIC' --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_sub_module --with-http_xslt_module --without-http_memcached_module --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/headers-more-nginx-module --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/nginx-auth-pam --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/nginx-cache-purge --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/nginx-echo --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/nginx-upstream-fair --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/ngx_http_substitutions_filter_module --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/memc-nginx-module --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/srcache-nginx-module --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/HttpRedisModule --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/redis2-nginx-module --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/ngx_devel_kit --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/set-misc-nginx-module --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/nginx-module-vts --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/ngx_brotli

- [ ] `wo -v`
Can't run due to above error

- [ ] `wp cli info --allow-root`
OS:	Linux 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php7.4
PHP version:	7.4.11
php.ini used:	/etc/php/7.4/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/root
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.4.0

- [ ] `curl -sL git.io/fjAp3 | sudo -E bash -`

Here the link to provide in your github issue : https://transfer.vtbox.net/3EuwB/wordops.txt

**Comment by VirtuBox** [comment]
Hello @ajaydsouza, 
can you run the following command : 

```bash
source /opt/wo/bin/activate
python3 -m pip install git+https://salsa.debian.org/apt-team/python-apt.git@1.6.y#egg=python-apt
```

If the second command fail, try this one : 
```bash
python3 -m pip install git+https://salsa.debian.org/apt-team/python-apt.git@1.1.y-xenial#egg=python-apt
```

**Comment by ajaydsouza** [comment]
Thanks. It looks like both failed.

```
(wo) root@isentthis:~# python3 -m pip install git+https://salsa.debian.org/apt-team/python-apt.git@1.1.y-xenial#egg=python-apt
Collecting python-apt
  Cloning https://salsa.debian.org/apt-team/python-apt.git (to revision 1.1.y-xenial) to /tmp/pip-install-09enywq7/python-apt
Building wheels for collected packages: python-apt
  Building wheel for python-apt (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/wo/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-09enywq7/python-apt/setup.py'"'"'; __file__='"'"'/tmp/pip-install-09enywq7/python-apt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-6mw2t1mq
       cwd: /tmp/pip-install-09enywq7/python-apt/
  Complete output (56 lines):
  W: [python3.6] DistUtilsExtra import error.
  W: [python3.6] Sphinx import error.
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/apt
  copying apt/utils.py -> build/lib.linux-x86_64-3.6/apt
  copying apt/debfile.py -> build/lib.linux-x86_64-3.6/apt
  copying apt/auth.py -> build/lib.linux-x86_64-3.6/apt
  copying apt/package.py -> build/lib.linux-x86_64-3.6/apt
  copying apt/cache.py -> build/lib.linux-x86_64-3.6/apt
  copying apt/__init__.py -> build/lib.linux-x86_64-3.6/apt
  copying apt/cdrom.py -> build/lib.linux-x86_64-3.6/apt
  creating build/lib.linux-x86_64-3.6/apt/progress
  copying apt/progress/text.py -> build/lib.linux-x86_64-3.6/apt/progress
  copying apt/progress/base.py -> build/lib.linux-x86_64-3.6/apt/progress
  copying apt/progress/__init__.py -> build/lib.linux-x86_64-3.6/apt/progress
  creating build/lib.linux-x86_64-3.6/aptsources
  copying aptsources/distro.py -> build/lib.linux-x86_64-3.6/aptsources
  copying aptsources/sourceslist.py -> build/lib.linux-x86_64-3.6/aptsources
  copying aptsources/distinfo.py -> build/lib.linux-x86_64-3.6/aptsources
  copying aptsources/__init__.py -> build/lib.linux-x86_64-3.6/aptsources
  running build_ext
  building 'apt_pkg' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/python
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/opt/wo/include -I/usr/include/python3.6m -c python/acquire.cc -o build/temp.linux-x86_64-3.6/python/acquire.o -std=c++11 -Wno-write-strings -DAPT_8_CLEANER_HEADERS -DAPT_9_CLEANER_HEADERS -DAPT_10_CLEANER_HEADERS
  python/acquire.cc: In function ‘PyObject* PkgAcquireNew(PyTypeObject*, PyObject*, PyObject*)’:
  python/acquire.cc:349:28: warning: ‘bool pkgAcquire::Setup(pkgAcquireStatus*, const string&)’ is deprecated: Use constructors, .SetLog and .GetLock as needed [-Wdeprecated-declarations]
       fetcher->Setup(progress);
                              ^
  In file included from /usr/include/apt-pkg/acquire-item.h:22:0,
                   from python/apt_pkgmodule.h:15,
                   from python/acquire.cc:26:
  /usr/include/apt-pkg/acquire.h:368:80: note: declared here
      APT_DEPRECATED_MSG("Use constructors, .SetLog and .GetLock as needed") bool Setup(pkgAcquireStatus *Progress = NULL, std::string const &Lock = "");
                                                                                  ^~~~~
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/opt/wo/include -I/usr/include/python3.6m -c python/acquire-item.cc -o build/temp.linux-x86_64-3.6/python/acquire-item.o -std=c++11 -Wno-write-strings -DAPT_8_CLEANER_HEADERS -DAPT_9_CLEANER_HEADERS -DAPT_10_CLEANER_HEADERS
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/opt/wo/include -I/usr/include/python3.6m -c python/apt_pkgmodule.cc -o build/temp.linux-x86_64-3.6/python/apt_pkgmodule.o -std=c++11 -Wno-write-strings -DAPT_8_CLEANER_HEADERS -DAPT_9_CLEANER_HEADERS -DAPT_10_CLEANER_HEADERS
  python/apt_pkgmodule.cc: In function ‘PyObject* PkgSystemLockInner(PyObject*, PyObject*)’:
  python/apt_pkgmodule.cc:571:24: error: ‘class pkgSystem’ has no member named ‘LockInner’
      bool res = _system->LockInner();
                          ^~~~~~~~~
  python/apt_pkgmodule.cc: In function ‘PyObject* PkgSystemUnLockInner(PyObject*, PyObject*)’:
  python/apt_pkgmodule.cc:592:24: error: ‘class pkgSystem’ has no member named ‘UnLockInner’; did you mean ‘UnLock’?
      bool res = _system->UnLockInner();
                          ^~~~~~~~~~~
                          UnLock
  python/apt_pkgmodule.cc: In function ‘PyObject* PkgSystemIsLocked(PyObject*, PyObject*)’:
  python/apt_pkgmodule.cc:613:24: error: ‘class pkgSystem’ has no member named ‘IsLocked’; did you mean ‘Lock’?
      bool res = _system->IsLocked();
                          ^~~~~~~~
                          Lock
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for python-apt
  Running setup.py clean for python-apt
Failed to build python-apt
Installing collected packages: python-apt
    Running setup.py install for python-apt ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/wo/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-09enywq7/python-apt/setup.py'"'"'; __file__='"'"'/tmp/pip-install-09enywq7/python-apt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-cy63x3dq/install-record.txt --single-version-externally-managed --compile --install-headers /opt/wo/include/site/python3.6/python-apt
         cwd: /tmp/pip-install-09enywq7/python-apt/
    Complete output (56 lines):
    W: [python3.6] DistUtilsExtra import error.
    W: [python3.6] Sphinx import error.
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/apt
    copying apt/utils.py -> build/lib.linux-x86_64-3.6/apt
    copying apt/debfile.py -> build/lib.linux-x86_64-3.6/apt
    copying apt/auth.py -> build/lib.linux-x86_64-3.6/apt
    copying apt/package.py -> build/lib.linux-x86_64-3.6/apt
    copying apt/cache.py -> build/lib.linux-x86_64-3.6/apt
    copying apt/__init__.py -> build/lib.linux-x86_64-3.6/apt
    copying apt/cdrom.py -> build/lib.linux-x86_64-3.6/apt
    creating build/lib.linux-x86_64-3.6/apt/progress
    copying apt/progress/text.py -> build/lib.linux-x86_64-3.6/apt/progress
    copying apt/progress/base.py -> build/lib.linux-x86_64-3.6/apt/progress
    copying apt/progress/__init__.py -> build/lib.linux-x86_64-3.6/apt/progress
    creating build/lib.linux-x86_64-3.6/aptsources
    copying aptsources/distro.py -> build/lib.linux-x86_64-3.6/aptsources
    copying aptsources/sourceslist.py -> build/lib.linux-x86_64-3.6/aptsources
    copying aptsources/distinfo.py -> build/lib.linux-x86_64-3.6/aptsources
    copying aptsources/__init__.py -> build/lib.linux-x86_64-3.6/aptsources
    running build_ext
    building 'apt_pkg' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/python
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/opt/wo/include -I/usr/include/python3.6m -c python/acquire.cc -o build/temp.linux-x86_64-3.6/python/acquire.o -std=c++11 -Wno-write-strings -DAPT_8_CLEANER_HEADERS -DAPT_9_CLEANER_HEADERS -DAPT_10_CLEANER_HEADERS
    python/acquire.cc: In function ‘PyObject* PkgAcquireNew(PyTypeObject*, PyObject*, PyObject*)’:
    python/acquire.cc:349:28: warning: ‘bool pkgAcquire::Setup(pkgAcquireStatus*, const string&)’ is deprecated: Use constructors, .SetLog and .GetLock as needed [-Wdeprecated-declarations]
         fetcher->Setup(progress);
                                ^
    In file included from /usr/include/apt-pkg/acquire-item.h:22:0,
                     from python/apt_pkgmodule.h:15,
                     from python/acquire.cc:26:
    /usr/include/apt-pkg/acquire.h:368:80: note: declared here
        APT_DEPRECATED_MSG("Use constructors, .SetLog and .GetLock as needed") bool Setup(pkgAcquireStatus *Progress = NULL, std::string const &Lock = "");
                                                                                    ^~~~~
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/opt/wo/include -I/usr/include/python3.6m -c python/acquire-item.cc -o build/temp.linux-x86_64-3.6/python/acquire-item.o -std=c++11 -Wno-write-strings -DAPT_8_CLEANER_HEADERS -DAPT_9_CLEANER_HEADERS -DAPT_10_CLEANER_HEADERS
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/opt/wo/include -I/usr/include/python3.6m -c python/apt_pkgmodule.cc -o build/temp.linux-x86_64-3.6/python/apt_pkgmodule.o -std=c++11 -Wno-write-strings -DAPT_8_CLEANER_HEADERS -DAPT_9_CLEANER_HEADERS -DAPT_10_CLEANER_HEADERS
    python/apt_pkgmodule.cc: In function ‘PyObject* PkgSystemLockInner(PyObject*, PyObject*)’:
    python/apt_pkgmodule.cc:571:24: error: ‘class pkgSystem’ has no member named ‘LockInner’
        bool res = _system->LockInner();
                            ^~~~~~~~~
    python/apt_pkgmodule.cc: In function ‘PyObject* PkgSystemUnLockInner(PyObject*, PyObject*)’:
    python/apt_pkgmodule.cc:592:24: error: ‘class pkgSystem’ has no member named ‘UnLockInner’; did you mean ‘UnLock’?
        bool res = _system->UnLockInner();
                            ^~~~~~~~~~~
                            UnLock
    python/apt_pkgmodule.cc: In function ‘PyObject* PkgSystemIsLocked(PyObject*, PyObject*)’:
    python/apt_pkgmodule.cc:613:24: error: ‘class pkgSystem’ has no member named ‘IsLocked’; did you mean ‘Lock’?
        bool res = _system->IsLocked();
                            ^~~~~~~~
                            Lock
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/wo/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-09enywq7/python-apt/setup.py'"'"'; __file__='"'"'/tmp/pip-install-09enywq7/python-apt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-cy63x3dq/install-record.txt --single-version-externally-managed --compile --install-headers /opt/wo/include/site/python3.6/python-apt Check the logs for full command output.
(wo) root@isentthis:~#

```

**Comment by ajaydsouza** [comment]
Is there a way for me to reinstall wordops - not sure if that will help fix it.

**Comment by VirtuBox** [comment]
Can you send me the output of the commands `dpkg --list | grep apt` and `dpkg --list | grep pkg` ?

Otherwise, this command should fix your current issue : 

```bash
python3 -m venv --system-site-packages /opt/wo
```

Let me know if WordOps work properly after running this command.

**Comment by ajaydsouza** [comment]
This command worked! Thank you very much. Any idea what happened?

**Comment by VirtuBox** [comment]
Hello @ajaydsouza, 
yes, python-apt package wasn't compiled properly on your server and that's why `wo` command failed. But I'm still trying to understand why python-apt compilation failed.

**Comment by ajaydsouza** [comment]
Thanks. Am not sure what happened either. The last update from a few days back went well with the wo update command and I thought so did this one.

Is there anything I can do to help debug?

**Comment by jasomdotnet** [comment]
I have simillar message after distro upgrade to 22.04

```
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 5, in <module>
    from wo.cli.main import main
ModuleNotFoundError: No module named 'wo'
```

**Comment by Unicom3000** [comment]
I got similar problem https://community.wordops.net/d/1808-error-traceback-most-recent-call-last-when-wo-installing
