### ISSUE TITLE
mysql error on raspberry pi 4

### ISSUE THREAD

**Issue by MohaBeacon** [WordOps/WordOps#359]
Start : wo-kernel [OK]
Adding repository for NGINX, please wait...
Adding repository for PHP, please wait...
Updating apt-cache [OK]
Installing APT packages [OK]
Applying Nginx configuration templates
Testing Nginx configuration [OK]
Restarting Nginx [OK]
Testing Nginx configuration [OK]
Restarting Nginx [OK]
Configuring php7.3-fpm
Restarting php7.3-fpm [OK]
Tuning MySQL configuration [OK]
Restarting mysql [KO]
Running pre-update checks [OK]
Setting up NGINX configuration [Done]
Setting up webroot [Done]
Downloading WordPress [Done]
Setting up database Traceback (most recent call last):
File "/opt/wo/lib/python3.7/site-packages/pymysql/connections.py", line 614, in connect
(self.host, self.port), self.connect_timeout, **kwargs
File "/usr/lib/python3.7/socket.py", line 727, in create_connection
raise err
File "/usr/lib/python3.7/socket.py", line 716, in create_connection
sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/bin/wo", line 8, in <module>
sys.exit(main())
File "/opt/wo/lib/python3.7/site-packages/wo/cli/main.py", line 102, in main
app.run()
File "/opt/wo/lib/python3.7/site-packages/cement/core/foundation.py", line 882, in run
return_val = self.controller._dispatch()
File "/opt/wo/lib/python3.7/site-packages/cement/core/controller.py", line 471, in _dispatch
return func()
File "/opt/wo/lib/python3.7/site-packages/cement/core/controller.py", line 471, in _dispatch
return func()
File "/opt/wo/lib/python3.7/site-packages/cement/core/controller.py", line 477, in _dispatch
return func()
File "/opt/wo/lib/python3.7/site-packages/wo/cli/plugins/site_create.py", line 375, in default
wo_wp_creds = setupwordpress(self, data, vhostonly)
File "/opt/wo/lib/python3.7/site-packages/wo/cli/plugins/site_functions.py", line 288, in setupwordpress
data = setupdatabase(self, data)
File "/opt/wo/lib/python3.7/site-packages/wo/cli/plugins/site_functions.py", line 201, in setupdatabase
.format(wo_db_name))
File "/opt/wo/lib/python3.7/site-packages/wo/core/mysql.py", line 71, in execute
connection = WOMysql.connect(self)
File "/opt/wo/lib/python3.7/site-packages/wo/core/mysql.py", line 35, in connect
read_default_file='/etc/mysql/conf.d/my.cnf')
File "/opt/wo/lib/python3.7/site-packages/pymysql/connections.py", line 353, in init
self.connect()
File "/opt/wo/lib/python3.7/site-packages/pymysql/connections.py", line 664, in connect
raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")

**Comment by idpokute** [comment]
Same issue happens on my rpi4 with raspbian 10.

**Comment by jtwooton** [comment]
Same issue happens on my VPS, Ubuntu 20.04
