### ISSUE TITLE
SyntaxError: invalid syntax pystache/parser.py

### ISSUE THREAD

**Issue by GitMac32** [WordOps/WordOps#397]
Setting up a new server and when it came time to install WO, I consistently started getting "Syntax Error: invalid syntax" right after the "running post-install steps". I'm not sure what changed with the recent "update" but it seems to have broken the install package. I've attempted to install across several machines, physical and virtual, and various distros and they all throw the same error originating in pystache/parser.py line 15: `NON_BLANK_RE = re.compile(ur'^(.)', re.M)`

Issue began occuring yesterday. Prior to that several of my machines have had successful installations of WO, with no issues at all. 
Including the requested info: 
:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
:~# wo info
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/opt/wo/lib/python3.8/site-packages/wo/cli/main.py", line 93, in main
    with app:
  File "/opt/wo/lib/python3.8/site-packages/cement/core/foundation.py", line 1501, in __enter__
    self.setup()
  File "/opt/wo/lib/python3.8/site-packages/cement/core/foundation.py", line 846, in setup
    self._setup_extension_handler()
  File "/opt/wo/lib/python3.8/site-packages/cement/core/foundation.py", line 1226, in _setup_extension_handler
    self.ext.load_extensions(self._meta.extensions)
  File "/opt/wo/lib/python3.8/site-packages/cement/core/extension.py", line 166, in load_extensions
    self.load_extension(ext)
  File "/opt/wo/lib/python3.8/site-packages/cement/core/extension.py", line 145, in load_extension
    __import__(ext_module, globals(), locals(), [], 0)
  File "/opt/wo/lib/python3.8/site-packages/cement/ext/ext_mustache.py", line 89, in <module>
    from pystache.renderer import Renderer
  File "/opt/wo/lib/python3.8/site-packages/pystache/__init__.py", line 9, in <module>
    from pystache.init import parse, render, Renderer, TemplateSpec
  File "/opt/wo/lib/python3.8/site-packages/pystache/init.py", line 8, in <module>
    from pystache.parser import parse
  File "/opt/wo/lib/python3.8/site-packages/pystache/parser.py", line 15
    NON_BLANK_RE = re.compile(ur'^(.)', re.M)
                                ^
SyntaxError: invalid syntax
:~# nginx -V
bash: nginx: command not found
:~# wo -v
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/opt/wo/lib/python3.8/site-packages/wo/cli/main.py", line 93, in main
    with app:
  File "/opt/wo/lib/python3.8/site-packages/cement/core/foundation.py", line 1501, in __enter__
    self.setup()
  File "/opt/wo/lib/python3.8/site-packages/cement/core/foundation.py", line 846, in setup
    self._setup_extension_handler()
  File "/opt/wo/lib/python3.8/site-packages/cement/core/foundation.py", line 1226, in _setup_extension_handler
    self.ext.load_extensions(self._meta.extensions)
  File "/opt/wo/lib/python3.8/site-packages/cement/core/extension.py", line 166, in load_extensions
    self.load_extension(ext)
  File "/opt/wo/lib/python3.8/site-packages/cement/core/extension.py", line 145, in load_extension
    __import__(ext_module, globals(), locals(), [], 0)
  File "/opt/wo/lib/python3.8/site-packages/cement/ext/ext_mustache.py", line 89, in <module>
    from pystache.renderer import Renderer
  File "/opt/wo/lib/python3.8/site-packages/pystache/__init__.py", line 9, in <module>
    from pystache.init import parse, render, Renderer, TemplateSpec
  File "/opt/wo/lib/python3.8/site-packages/pystache/init.py", line 8, in <module>
    from pystache.parser import parse
  File "/opt/wo/lib/python3.8/site-packages/pystache/parser.py", line 15
    NON_BLANK_RE = re.compile(ur'^(.)', re.M)
                                ^
SyntaxError: invalid syntax
:~# wp cli info --allow-root
/usr/bin/env: ‘php’: No such file or directory
:~# curl -sL git.io/fjAp3 |sudo -E bash-
sudo: bash-: command not found
(23) Failed writing body
:~#

**Comment by tdmrut** [comment]
Same here

**Comment by jnimmo** [comment]
This issue can be resolved by installing setuptools 57.5.0 prior to installing wordops
pip install setuptools==57.5.0
There's an error logged when trying to install pystache which appears to be related to python 2_to_3 conversion happening at build time.

**Comment by VirtuBox** [comment]
Hello everyone, I'm working on a fix asap

**Comment by pc-tzimmerman** [comment]
We have different definitions of `ASAP` lol
