### ISSUE TITLE
Error during "Running post-install steps" -- `wo` command no longer runnable

### ISSUE THREAD

**Issue by Slapbox** [WordOps/WordOps#417]
After this failure, the `wo` command no longer works as intended, throwing this same error whenever `wo` is run.

```
[~] wo update
Downloading update script        [Done]
updating WordOps, please wait...

Welcome to WordOps install/update script v3.14.0

Installing wo dependencies      [OK]
Installing WordOps      [OK]
Running post-install steps      [OK]
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 5, in <module>
    from wo.cli.main import main
  File "/opt/wo/lib/python3.5/site-packages/wo/__init__.py", line 1, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
AttributeError: module 'pkg_resources' has no attribute 'declare_namespace'
WordOps (wo) upgrade to v3.14.0 was succesfull!
Changelog is available on https://github.com/WordOps/WordOps/releases/tag/v3.14.0

```

System Information

- [x] `lsb_release -a`

```
[~] lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch
```

- [x] `wo info`

_Cannot be run_

- [x] `nginx -V`

```
nginx version: nginx/1.18.0 (WordOps Nginx-wo)
built with OpenSSL 1.1.1g  21 Apr 2020 (running with OpenSSL 1.1.1j  16 Feb 2021)
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/usr/src/packages/BUILD=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -flto -ffat-lto-objects -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-z,relro -fPIC -flto -ffat-lto-objects' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo' --with-debug --with-pcre-jit --with-file-aio --with-threads --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-openssl-opt='zlib enable-ec_nistp_64_gcc_128 enable-tls1_3 no-ssl3-method -fPIC' --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_sub_module --with-http_xslt_module --without-http_memcached_module --add-module=/usr/src/packages/BUILD/debian/modules/headers-more-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/nginx-auth-pam --add-module=/usr/src/packages/BUILD/debian/modules/nginx-cache-purge --add-module=/usr/src/packages/BUILD/debian/modules/nginx-echo --add-module=/usr/src/packages/BUILD/debian/modules/nginx-upstream-fair --add-module=/usr/src/packages/BUILD/debian/modules/ngx_http_substitutions_filter_module --add-module=/usr/src/packages/BUILD/debian/modules/memc-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/srcache-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/HttpRedisModule --add-module=/usr/src/packages/BUILD/debian/modules/redis2-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/ngx_devel_kit --add-module=/usr/src/packages/BUILD/debian/modules/set-misc-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/nginx-module-vts --add-module=/usr/src/packages/BUILD/debian/modules/ngx_brotli
```

- [x] `wo -v`

_Cannot be run_

- [x] `wp cli info --allow-root`

```
[~] wp cli info --allow-root
OS:     Linux 4.9.0-17-amd64 #1 SMP Debian 4.9.290-1 (2021-12-12) x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php7.4
PHP version:    7.4.27
php.ini used:   /etc/php/7.4/cli/php.ini
MySQL binary:   /usr/bin/mysql
MySQL version:  mysql  Ver 15.1 Distrib 10.5.13-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
SQL modes:      STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /root
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.6.0
```

- [x] `curl -sL git.io/fjAp3 | sudo -E bash -`

```

Here the link to provide in your github issue : <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by Slapbox** [comment]
Reboot and reinstallation from scratch have no effect.

Also tried `pip install --upgrade --force setuptools` and `pip3 install --upgrade --force setuptools` - These commands complete successfully, but do not make any difference in the issue.

**Comment by ridgegate** [comment]
Not sure if the commands below help. 

sudo pip install -U pip setuptools
sudo python3 -m pip install -I wordops

**Comment by Slapbox** [comment]
Indeed that does work! Despite the fact that an error is thrown during the second command, it seems to all be working now.

If you don't mind elaborating - what exactly does `sudo python3 -m pip install -I wordops` do that installing WordOps via the method mentioned in the Readme file doesn't?

**The error** (which again, didn't seem to cause any actual problems):
```
Collecting wordops
  Using cached wordops-3.14.0-py3-none-any.whl (221 kB)
Collecting pystache>=0.5.4
  Downloading pystache-0.6.0.tar.gz (78 kB)
     |████████████████████████████████| 78 kB 5.1 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpb53hxg10
       cwd: /tmp/pip-install-07sgzczu/pystache_e7461c448cff45449961216c8004174c
  Complete output (17 lines):
  Traceback (most recent call last):
    File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/usr/local/lib/python3.5/dist-packages/setuptools/build_meta.py", line 150, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/usr/local/lib/python3.5/dist-packages/setuptools/build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "/usr/local/lib/python3.5/dist-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 183
      command = f"pandoc -f markdown-smart --write=rst --output={rst_temp_path} {md_path}"
                                                                                         ^
  SyntaxError: invalid syntax
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/3f/e7/8750ba6c6101d6aa5ceeb20c013adf2c6f3554a12c71d75654b468404bfa/pystache-0.6.0.tar.gz#sha256=93bf92b2149a4c4b58d12142e2c4c6dd5c08d89e4c95afccd4b6efe2ee1d470d (from https://pypi.org/simple/pystache/). Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.5/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpb53hxg10 Check the logs for full command output.
```

**Comment by ridgegate** [comment]
I pulled those commands from another issue or forum.. I need to dig it out what it does if I could find it. Glad it is working! Thank you @VirtuBox for your work!

**Comment by Slapbox** [comment]
@VirtuBox - `wo update` breaks things in the same way when upgrading to 3.14.1. The same commands @ridgegate mentioned needed to be run again after `wo update` to fix it. Any thoughts?

**Comment by s-a-s-k-i-a** [comment]
+1

**Comment by s-a-s-k-i-a** [comment]
Any news on this? wo is still broken on my most important server

**Comment by Slapbox** [comment]
@s-a-s-k-i-a you should check the issue template under _**New issue**_ and then include all of the data it asks for in a comment here. 

I don't know how to help fix this for you unfortunately, but I know that anyone who does know how is going to need some or all of that information.

**Comment by s-a-s-k-i-a** [comment]
I was able to fix it!

This is how:

run these commands:
1. `sudo python3 get-pip.py`
2. `sudo pip install -U pip setuptools`
3. `sudo python3 -m pip install -I wordops` (we will see an error message within now triggered output, but it will work nevertheless)
4. checking wo with `wo -v`
Invalid syntax gone! Things are back to normal.

**Comment by Slapbox** [comment]
@VirtuBox this issue persists in 3.14.2 and occurs every time we upgrade. Do you have any ideas?

@s-a-s-k-i-a, do you need to re-run your fix after upgrading WordOps? For us, we need to re-run the steps that helped us on every upgrade.

**Comment by s-a-s-k-i-a** [comment]
@Slapbox Yes, I have to re-run above steps after every update. Also since last update I am also seeing the php74-geoip can't be found problem described here: https://community.wordops.net/d/1258-unable-to-locate-package-php74-geoip
