### ISSUE TITLE
Git unsafe repository when creating site

### ISSUE THREAD

**Issue by tersor** [WordOps/WordOps#427]
[System information](https://gist.github.com/tersor/3096761985a991882802e760f8482516).

I get the following error when creating a new site:

```
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/opt/wo/lib/python3.8/site-packages/wo/cli/main.py", line 102, in main
    app.run()
  File "/opt/wo/lib/python3.8/site-packages/cement/core/foundation.py", line 882, in run
    return_val = self.controller._dispatch()
  File "/opt/wo/lib/python3.8/site-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/opt/wo/lib/python3.8/site-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/opt/wo/lib/python3.8/site-packages/cement/core/controller.py", line 477, in _dispatch
    return func()
  File "/opt/wo/lib/python3.8/site-packages/wo/cli/plugins/site_create.py", line 589, in default
    WOGit.add(self, ["{0}/conf/nginx".format(wo_site_webroot)],
  File "/opt/wo/lib/python3.8/site-packages/wo/core/git.py", line 32, in add
    status = wogit.status("-s")
  File "/opt/wo/lib/python3.8/site-packages/sh.py", line 1520, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/opt/wo/lib/python3.8/site-packages/sh.py", line 784, in __init__
    self.wait()
  File "/opt/wo/lib/python3.8/site-packages/sh.py", line 841, in wait
    self.handle_command_exit_code(exit_code)
  File "/opt/wo/lib/python3.8/site-packages/sh.py", line 865, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_128:

  RAN: /usr/bin/git -C /var/www/domain.tld/conf/nginx status -s

  STDOUT:


  STDERR:
fatal: unsafe repository ('/var/www/domain.tld/conf/nginx' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /var/www/domain.tld/conf/nginx
```

I would think this is related to [this git vulnerability](https://github.blog/2022-04-12-git-security-vulnerability-announced/). When WordOps creates a new site, it uses git to track changes in `/var/www/domain.tld/conf/nginx`. Since the folder is owned by www-data, WordOps needs to add this folder to the `safe.directory` global config.

**Comment by sschemedotcom** [comment]
Has anyone solved this problem yet? I also got the same error as above

**Comment by vikas5914** [comment]
Please try this `git config --global --add safe.directory *`

**Comment by tersor** [comment]
In order to use the wildcard solution mentioned above, we needed to install the latest stable git version maintained by the Ubuntu Git Maintainers team:

```
add-apt-repository ppa:git-core/ppa -y
apt upgrade git -y
```

Then edit `/root/.gitconfig` and add the following line under `[safe]` section:

```
[safe]
  directory = *
```

This way future `site create` commands will not raise any errors.

**Comment by sschemedotcom** [comment]
Great, problem solved

**Comment by deludwig16** [comment]
@tersor thank you so much!

**Comment by VirtuBox** [comment]
@tersor do you know if the same issue exist on debian ?

**Comment by tersor** [comment]
@VirtuBox I have not tested on debian, but I would be surprised if it didnt exist.

**Comment by tersor** [comment]
@AlexZanderD

Yes, after WO is updated, you can remove the `directory = *` line.

Then you have to add each of your existing sites (if not already present in `/root/.gitconfig`):

```
git config --global --add safe.directory /var/www/domain.tld/conf/nginx
```

**Comment by AlexZanderD** [comment]
> @AlexZanderD
> 
> Yes, after WO is updated, you can remove the `directory = *` line.
> 
> Then you have to add each of your existing sites (if not already present in `/root/.gitconfig`):
> 
> ```
> git config --global --add safe.directory /var/www/domain.tld/conf/nginx
> ```

Many thanks to you for reply and for workaround!

**Comment by arkdev1** [comment]
Hi @VirtuBox, sorry to use this closed issue, today it "came back".

```
13:32:56-user@<REDACTED>-hel1-1:~$ sudo -E wo site create subdomain.domain.com --php84 --ngxblocker --letsencrypt --dns=dns_cf --hsts
Running pre-update checks       [OK]
Setting up NGINX configuration 	[Done]
Setting up webroot 		[Done]
Testing Nginx configuration     [OK]
Reloading Nginx                 [OK]
Successfully created site http://subdomain.domain.com
Certificate type : subdomain
Validation mode : DNS mode with dns_cf
Issuing SSL cert with acme.sh   [OK]
Deploying SSL cert              [OK]
Adding /var/www/subdomain.domain.com/conf/nginx/hsts.conf
Adding HTTPS redirection        [OK]
Testing Nginx configuration     [OK]
Reloading Nginx                 [OK]
Congratulations! Successfully Configured SSL on https://subdomain.domain.com
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/wo/lib/python3.12/site-packages/wo/cli/main.py", line 102, in main
    app.run()
  File "/opt/wo/lib/python3.12/site-packages/cement/core/foundation.py", line 882, in run
    return_val = self.controller._dispatch()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/wo/lib/python3.12/site-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
           ^^^^^^
  File "/opt/wo/lib/python3.12/site-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
           ^^^^^^
  File "/opt/wo/lib/python3.12/site-packages/cement/core/controller.py", line 477, in _dispatch
    return func()
           ^^^^^^
  File "/opt/wo/lib/python3.12/site-packages/wo/cli/plugins/site_create.py", line 652, in default
    WOGit.add(self, ["{0}/conf/nginx".format(wo_site_webroot)],
  File "/opt/wo/lib/python3.12/site-packages/wo/core/git.py", line 33, in add
    status = wogit.status("-s")
             ^^^^^^^^^^^^^^^^^^
  File "/opt/wo/lib/python3.12/site-packages/sh.py", line 1511, in __call__
    rc = self.__class__.RunningCommandCls(cmd, call_args, stdin, stdout, stderr)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/wo/lib/python3.12/site-packages/sh.py", line 734, in __init__
    self.wait()
  File "/opt/wo/lib/python3.12/site-packages/sh.py", line 796, in wait
    self.handle_command_exit_code(exit_code)
  File "/opt/wo/lib/python3.12/site-packages/sh.py", line 823, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_128: 

  RAN: /usr/bin/git -C /var/www/subdomain.domain.com/conf/nginx status -s

  STDOUT:


  STDERR:
fatal: detected dubious ownership in repository at '/var/www/subdomain.domain.com/conf/nginx'
To add an exception for this directory, call:

	git config --global --add safe.directory /var/www/subdomain.domain.com/conf/nginx

```

Here the VPS details, i'm using WordOps v3.22.0.

```
PRETTY_NAME="Ubuntu 24.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.3 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

NGINX (1.28.0 ):

user                             www-data
worker_processes                 auto
worker_connections               50000
keepalive_timeout                8
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 ::1 
PHP 7.4 is not installed
PHP 8.0 is not installed
PHP 8.1 is not installed
PHP 8.2 is not installed
PHP 8.3 is not installed

PHP (8.4.14):

user                             
expose_php                       Off
memory_limit                     2048M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php84-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9184

MySQL (15.2) on localhost:

port                             3306
wait_timeout                     60
interactive_timeout              28800
max_used_connections             
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

```
