### ISSUE TITLE
Wo error

### ISSUE THREAD

**Issue by itfs1992** [WordOps/WordOps#428]
`Traceback (most recent call last):
  File "/opt/wo/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/opt/wo/lib/python3.6/site-packages/wo/cli/main.py", line 93, in main
    with app:
  File "/opt/wo/lib/python3.6/site-packages/cement/core/foundation.py", line 1501, in __enter__
    self.setup()
  File "/opt/wo/lib/python3.6/site-packages/cement/core/foundation.py", line 835, in setup
    __import__(self._meta.bootstrap, globals(), locals(), [], 0)
  File "/opt/wo/lib/python3.6/site-packages/wo/cli/bootstrap.py", line 7, in <module>
    from wo.cli.controllers.base import WOBaseController
  File "/opt/wo/lib/python3.6/site-packages/wo/cli/controllers/base.py", line 5, in <module>
    from wo.core.variables import WOVar
  File "/opt/wo/lib/python3.6/site-packages/wo/core/variables.py", line 13, in <module>
    class WOVar():
  File "/opt/wo/lib/python3.6/site-packages/wo/core/variables.py", line 67, in WOVar
    config.read(os.path.expanduser("~") + '/.gitconfig')
  File "/usr/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.6/configparser.py", line 1092, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '/root/.gitconfig' [line  6]: option 'directory' in section 'safe' already exists`

**Comment by janiosarmento** [comment]
This is the same as #427

**Comment by itfs1992** [comment]
How do you fix the error?

> This is the same as #427

**Comment by janiosarmento** [comment]
There's no fix yet.
  
​
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  Janio   Sarmento
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
​ ***@***.*** ***@***.***)
  
Twitter (https://twitter.com/janiosarmento)  |  Facebook.com (https://facebook.com/janiosarmento)  |  Instagram (https://instagram.com/janiosarnento)  |  Blog (https://janio.sarmento.org)

**Comment by itfs1992** [comment]
Is there no other way to fix the error? Do I have to wait for the update?

**Comment by sschemedotcom** [comment]
The web is still created although error, should normal use, or wait for updates and then create it

**Comment by itfs1992** [comment]
Can't add new site

**Comment by tersor** [comment]
@itfs1992 [Try this](https://github.com/WordOps/WordOps/issues/427#issuecomment-1104788407).

**Comment by s-a-s-k-i-a** [comment]
Seeing the same issue, whenever trying to run a WO command. No matter which one; I am given this output:

`root@srv:~# wo --version
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/wo/cli/main.py", line 93, in main
    with app:
  File "/usr/local/lib/python3.8/dist-packages/cement/core/foundation.py", line 1501, in __enter__
    self.setup()
  File "/usr/local/lib/python3.8/dist-packages/cement/core/foundation.py", line 835, in setup
    __import__(self._meta.bootstrap, globals(), locals(), [], 0)
  File "/usr/local/lib/python3.8/dist-packages/wo/cli/bootstrap.py", line 7, in <module>
    from wo.cli.controllers.base import WOBaseController
  File "/usr/local/lib/python3.8/dist-packages/wo/cli/controllers/base.py", line 5, in <module>
    from wo.core.variables import WOVar
  File "/usr/local/lib/python3.8/dist-packages/wo/core/variables.py", line 13, in <module>
    class WOVar():
  File "/usr/local/lib/python3.8/dist-packages/wo/core/variables.py", line 67, in WOVar
    config.read(os.path.expanduser("~") + '/.gitconfig')
  File "/usr/lib/python3.8/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.8/configparser.py", line 1093, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from '/root/.gitconfig' [line  6]: option 'directory' in section 'safe' already exists`

I tried several fixes, including the following:
https://github.com/WordOps/WordOps/issues/427#issuecomment-1104788407
and
reinstalling python3.

Any help or advice is highly appreciated..
