### ISSUE TITLE
Issue running wo after distro upgrade to 22.04

### ISSUE THREAD

**Issue by jasomdotnet** [WordOps/WordOps#478]
I have simillar message after distro upgrade to 22.04 like in #334 

```
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 5, in <module>
    from wo.cli.main import main
ModuleNotFoundError: No module named 'wo'
```

**System Information**

`lsb_release -a`

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

`wo info`

```
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 5, in <module>
    from wo.cli.main import main
ModuleNotFoundError: No module named 'wo'
```

`nginx -V`

```
nginx version: nginx/1.22.1 (WordOps Nginx-wo)
built with OpenSSL 1.1.1f  31 Mar 2020
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-4yy9oe/nginx-1.22.1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -flto -ffat-lto-objects -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -fPIC -flto -ffat-lto-objects' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo' --with-debug --with-pcre-jit --with-file-aio --with-threads --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-openssl-opt='zlib enable-ec_nistp_64_gcc_128 enable-tls1_3 no-ssl3-method -fPIC' --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_sub_module --with-http_xslt_module --without-http_memcached_module --add-module=/build/nginx-4yy9oe/nginx-1.22.1/debian/modules/headers-more-nginx-module --add-module=/build/nginx-4yy9oe/nginx-1.22.1/debian/modules/nginx-auth-pam --add-module=/build/nginx-4yy9oe/nginx-1.22.1/debian/modules/nginx-cache-purge --add-module=/build/nginx-4yy9oe/nginx-1.22.1/debian/modules/nginx-echo --add-module=/build/nginx-4yy9oe/nginx-1.22.1/debian/modules/nginx-upstream-fair --add-module=/build/nginx-4yy9oe/nginx-1.22.1/debian/modules/ngx_http_substitutions_filter_module --add-module=/build/nginx-4yy9oe/nginx-1.22.1/debian/modules/memc-nginx-module --add-module=/build/nginx-4yy9oe/nginx-1.22.1/debian/modules/srcache-nginx-module --add-module=/build/nginx-4yy9oe/nginx-1.22.1/debian/modules/HttpRedisModule --add-module=/build/nginx-4yy9oe/nginx-1.22.1/debian/modules/redis2-nginx-module --add-module=/build/nginx-4yy9oe/nginx-1.22.1/debian/modules/ngx_devel_kit --add-module=/build/nginx-4yy9oe/nginx-1.22.1/debian/modules/set-misc-nginx-module --add-module=/build/nginx-4yy9oe/nginx-1.22.1/debian/modules/nginx-module-vts --add-module=/build/nginx-4yy9oe/nginx-1.22.1/debian/modules/ngx_brotli
```

`wp cli info --allow-root`

```
OS:	Linux 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php8.1
PHP version:	8.1.12
php.ini used:	/etc/php/8.1/cli/php.ini
MySQL binary:	/usr/bin/mysql
MySQL version:	mysql  Ver 15.1 Distrib 10.6.7-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
SQL modes:	
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/var/www
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.6.0
```

`source /opt/wo/bin/activate
python3 -m pip install git+https://salsa.debian.org/apt-team/python-apt.git@1.6.y#egg=python-apt`

```
Collecting python-apt
  Cloning https://salsa.debian.org/apt-team/python-apt.git (to revision 1.6.y) to /tmp/pip-install-ys9pswll/python-apt_473e789d22ee4cc88e86a308d6b53e47
  Running command git clone --filter=blob:none --quiet https://salsa.debian.org/apt-team/python-apt.git /tmp/pip-install-ys9pswll/python-apt_473e789d22ee4cc88e86a308d6b53e47
  fatal: unable to access 'https://salsa.debian.org/apt-team/python-apt.git/': Could not resolve host: salsa.debian.org
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://salsa.debian.org/apt-team/python-apt.git /tmp/pip-install-ys9pswll/python-apt_473e789d22ee4cc88e86a308d6b53e47 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://salsa.debian.org/apt-team/python-apt.git /tmp/pip-install-ys9pswll/python-apt_473e789d22ee4cc88e86a308d6b53e47 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

`python3 -m pip install git+https://salsa.debian.org/apt-team/python-apt.git@1.1.y-xenial#egg=python-apt`

```
Collecting python-apt
  Cloning https://salsa.debian.org/apt-team/python-apt.git (to revision 1.1.y-xenial) to /tmp/pip-install-6l0hjr21/python-apt_8a5e484c0b884dfa9e14b099c64efb73
  Running command git clone --filter=blob:none --quiet https://salsa.debian.org/apt-team/python-apt.git /tmp/pip-install-6l0hjr21/python-apt_8a5e484c0b884dfa9e14b099c64efb73
  fatal: unable to access 'https://salsa.debian.org/apt-team/python-apt.git/': Could not resolve host: salsa.debian.org
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://salsa.debian.org/apt-team/python-apt.git /tmp/pip-install-6l0hjr21/python-apt_8a5e484c0b884dfa9e14b099c64efb73 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://salsa.debian.org/apt-team/python-apt.git /tmp/pip-install-6l0hjr21/python-apt_8a5e484c0b884dfa9e14b099c64efb73 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by VirtuBox** [comment]
Hello @jasomdotnet,
you just have to reinstall WordOps with `wget -qO wo wops.cc && sudo bash wo`, it should fix your issue.
Otherwise run the following commands : 
```bash
source /opt/wo/bin/activate
pip uninstall python-apt
```
Then reinstall WordOps with the previous install command.
I will publish a guide in the next few days about Debian/Ubuntu distro upgrade.

**Comment by jasomdotnet** [comment]
none worked. i tried to distro upgrade twice so I thing I will go "install new server" way
