### ISSUE TITLE
error install Wordops !! 

### ISSUE THREAD

**Issue by npivaut** [WordOps/WordOps#497]
Hello, 

```
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/main.py", line 93, in main
    with app:
  File "/opt/wo/lib/python3.10/site-packages/cement/core/foundation.py", line 1501, in __enter__
    self.setup()
  File "/opt/wo/lib/python3.10/site-packages/cement/core/foundation.py", line 852, in setup
    self._setup_plugin_handler()
  File "/opt/wo/lib/python3.10/site-packages/cement/core/foundation.py", line 1339, in _setup_plugin_handler
    self.plugin.load_plugins(self.plugin.get_enabled_plugins())
  File "/opt/wo/lib/python3.10/site-packages/cement/ext/ext_plugin.py", line 290, in load_plugins
    self.load_plugin(plugin_name)
  File "/opt/wo/lib/python3.10/site-packages/cement/ext/ext_plugin.py", line 259, in load_plugin
    if self._load_plugin_from_bootstrap(plugin_name, self.bootstrap):
  File "/opt/wo/lib/python3.10/site-packages/cement/ext/ext_plugin.py", line 225, in _load_plugin_from_bootstrap
    __import__(full_module, globals(), locals(), [], 0)
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/plugins/debug.py", line 11, in <module>
    from wo.cli.plugins.site_functions import logwatch
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/plugins/site_functions.py", line 12, in <module>
    from wo.cli.plugins.sitedb import getSiteInfo
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/plugins/sitedb.py", line 6, in <module>
    from wo.cli.plugins.models import SiteDB
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/plugins/models.py", line 3, in <module>
    from wo.core.database import Base
  File "/opt/wo/lib/python3.10/site-packages/wo/core/database.py", line 9, in <module>
    engine = create_engine(WOVar.wo_db_uri, convert_unicode=True)
  File "<string>", line 2, in create_engine
  File "/opt/wo/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/opt/wo/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 693, in create_engine
    raise TypeError(
TypeError: Invalid argument(s) 'convert_unicode' sent to create_engine(), using configuration SQLiteDialect_pysqlite/QueuePool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.
```

System Information

```
serveur01@PC-AMD-STARK:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
serveur01@PC-AMD-STARK:~$ wo info
WordOps (wo) require an username & and an email address to configure Git (used to save server configurations)
Your informations will ONLY be stored locally
Enter your name: admin01
Enter your email: pivautnicolas@yahoo.com
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/main.py", line 93, in main
    with app:
  File "/opt/wo/lib/python3.10/site-packages/cement/core/foundation.py", line 1501, in __enter__
    self.setup()
  File "/opt/wo/lib/python3.10/site-packages/cement/core/foundation.py", line 835, in setup
    __import__(self._meta.bootstrap, globals(), locals(), [], 0)
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/bootstrap.py", line 7, in <module>
    from wo.cli.controllers.base import WOBaseController
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/controllers/base.py", line 5, in <module>
    from wo.core.variables import WOVar
  File "/opt/wo/lib/python3.10/site-packages/wo/core/variables.py", line 14, in <module>
    class WOVar():
  File "/opt/wo/lib/python3.10/site-packages/wo/core/variables.py", line 100, in WOVar
    copy2(os.path.expanduser("~") + '/.gitconfig', '/root/.gitconfig')
  File "/usr/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/root/.gitconfig'
serveur01@PC-AMD-STARK:~$ nginx -V
Command 'nginx' not found, but can be installed with:
sudo apt install nginx-core    # version 1.18.0-6ubuntu14.3, or
sudo apt install nginx-extras  # version 1.18.0-6ubuntu14.3
sudo apt install nginx-light   # version 1.18.0-6ubuntu14.3
serveur01@PC-AMD-STARK:~$ wo -v
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/main.py", line 93, in main
    with app:
  File "/opt/wo/lib/python3.10/site-packages/cement/core/foundation.py", line 1501, in __enter__
    self.setup()
  File "/opt/wo/lib/python3.10/site-packages/cement/core/foundation.py", line 835, in setup
    __import__(self._meta.bootstrap, globals(), locals(), [], 0)
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/bootstrap.py", line 7, in <module>
    from wo.cli.controllers.base import WOBaseController
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/controllers/base.py", line 5, in <module>
    from wo.core.variables import WOVar
  File "/opt/wo/lib/python3.10/site-packages/wo/core/variables.py", line 14, in <module>
    class WOVar():
  File "/opt/wo/lib/python3.10/site-packages/wo/core/variables.py", line 100, in WOVar
    copy2(os.path.expanduser("~") + '/.gitconfig', '/root/.gitconfig')
  File "/usr/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/root/.gitconfig'
serveur01@PC-AMD-STARK:~$ wp cli info --allow-root
/usr/bin/env: ‘php’: No such file or directory
serveur01@PC-AMD-STARK:~$ curl -sL git.io/fjAp3 | sudo -E bash -
[sudo] password for serveur01:

Here the link to provide in your github issue : Could not upload empty file
```

Thank you

**Comment by regys2011** [comment]
Hi, I am also having the same problem.

I did several tests on Debian 10.11.
On Ubuntu 20, 22
however, the same error persists. I already deleted and reinstalled Wordops with the command ## sudo rm -f /usr/local/bin/wo && wget -qO wo wops.cc && sudo bash wo ##
but nothing.

**Comment by hoangmme** [comment]
I am also having the same problem.

**Comment by VirtuBox** [comment]
Issue has been fixed in the last release.

Please update WordOps with the command `wo update` or launch again the install command `wget -qO wo wops.cc && sudo bash wo`.

**Comment by kokohcokisiregar** [comment]
> Issue has been fixed in the last release.
> 
> Please update WordOps with the command `wo update` or launch again the install command `wget -qO wo wops.cc && sudo bash wo`.

thank you so much...

**Comment by hoangmme** [comment]
> Issue has been fixed in the last release.
> 
> Please update WordOps with the command `wo update` or launch again the install command `wget -qO wo wops.cc && sudo bash wo`.

thank for your help, it working.
