### ISSUE TITLE
Error "Traceback (most recent call last)" when WO installing

### ISSUE THREAD

**Issue by Unicom3000** [WordOps/WordOps#498]
I tried installing WO multiple times on 3 VPS (in Europe and USA) with Ubuntu Server 22.04.1 / 20.04.5 / and upgraded 22.04 from 20.04. 
Another 2-3 weeks ago everything was fine and I deployed WordOps on 2 VPS from the same cohort.

Details is there: https://community.wordops.net/d/1808-error-traceback-most-recent-call-last-when-wo-installing

System Information
- [x] `lsb_release -a`
```
root@NYC768:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
root@NYC768:~#
```
- [x] `wo info`
- [x]  `wo -v`
```
root@NYC768:~# wo info
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/opt/wo/lib/python3.8/site-packages/wo/cli/main.py", line 93, in main
    with app:
  File "/opt/wo/lib/python3.8/site-packages/cement/core/foundation.py", line 1501, in __enter__
    self.setup()
  File "/opt/wo/lib/python3.8/site-packages/cement/core/foundation.py", line 852, in setup
    self._setup_plugin_handler()
  File "/opt/wo/lib/python3.8/site-packages/cement/core/foundation.py", line 1339, in _setup_plugin_handler
    self.plugin.load_plugins(self.plugin.get_enabled_plugins())
  File "/opt/wo/lib/python3.8/site-packages/cement/ext/ext_plugin.py", line 290, in load_plugins
    self.load_plugin(plugin_name)
  File "/opt/wo/lib/python3.8/site-packages/cement/ext/ext_plugin.py", line 259, in load_plugin
    if self._load_plugin_from_bootstrap(plugin_name, self.bootstrap):
  File "/opt/wo/lib/python3.8/site-packages/cement/ext/ext_plugin.py", line 225, in _load_plugin_from_bootstrap
    __import__(full_module, globals(), locals(), [], 0)
  File "/opt/wo/lib/python3.8/site-packages/wo/cli/plugins/debug.py", line 11, in <module>
    from wo.cli.plugins.site_functions import logwatch
  File "/opt/wo/lib/python3.8/site-packages/wo/cli/plugins/site_functions.py", line 12, in <module>
    from wo.cli.plugins.sitedb import getSiteInfo
  File "/opt/wo/lib/python3.8/site-packages/wo/cli/plugins/sitedb.py", line 6, in <module>
    from wo.cli.plugins.models import SiteDB
  File "/opt/wo/lib/python3.8/site-packages/wo/cli/plugins/models.py", line 3, in <module>
    from wo.core.database import Base
  File "/opt/wo/lib/python3.8/site-packages/wo/core/database.py", line 9, in <module>
    engine = create_engine(WOVar.wo_db_uri, convert_unicode=True)
  File "<string>", line 2, in create_engine
  File "/opt/wo/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/opt/wo/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 693, in create_engine
    raise TypeError(
TypeError: Invalid argument(s) 'convert_unicode' sent to create_engine(), using configuration SQLiteDialect_pysqlite/QueuePool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.
```
- [x] `nginx -V`
root@NYC768:~# nginx -V
Command 'nginx' not found, but can be installed with:

- [x] `wp cli info --allow-root`
root@NYC768:~# wp cli info --allow-root
/usr/bin/env: ‘php’: No such file or directory

- [x] `curl -sL git.io/fjAp3 | sudo -E bash -`
Here the link to provide in your github issue : Could not upload empty file

**Comment by kokohcokisiregar** [comment]
i having the same problem, what is the solution?

**Comment by VirtuBox** [comment]
Hello,

thanks for your report, I'm working on it.

**Comment by kokohcokisiregar** [comment]
thank you

**Comment by Yelvann** [comment]
Also happens here. Same error. Tried different fixes and nothing works. 
During post install, when executes wo sync, is when the error is thrown. 
Thanks for having a look.

**Comment by VirtuBox** [comment]
Issue has been fixed in the last release.

Please update WordOps with the command `wo update` or launch again the install command `wget -qO wo wops.cc && sudo bash wo`.

**Comment by Yelvann** [comment]
> Issue has been fixed in the last release.
> 
> Please update WordOps with the command `wo update` or launch again the install command `wget -qO wo wops.cc && sudo bash wo`.

Thanks. It works back again.
