### ISSUE TITLE
Installation fails after upgrade from Ubuntu 16.04 to 18.04 and switch from EasyEngine

### ISSUE THREAD

**Issue by vincenzocasu** [WordOps/WordOps#510]
Hello, I'm having trouble switching to WO from EasyEngine. I state that I just migrated from 16.04 to 18.04 which was the minimum version supported by WO. I ran the install command, but I get these errors and can't figure out how to fix.

I also tried manually installing the latest Python release, but it won't start.

#sudo bash wo

Welcome to WordOps install/update script v3.16.3

Installing wo dependencies      [OK]
Installing WordOps      [OK]
Running post-install steps      [OK]
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/wo/cli/main.py", line 93, in main
    with app:
  File "/opt/wo/lib/python3.11/site-packages/cement/core/foundation.py", line 1501, in __enter__
    self.setup()
  File "/opt/wo/lib/python3.11/site-packages/cement/core/foundation.py", line 852, in setup
    self._setup_plugin_handler()
  File "/opt/wo/lib/python3.11/site-packages/cement/core/foundation.py", line 1339, in _setup_plugin_handler
    self.plugin.load_plugins(self.plugin.get_enabled_plugins())
  File "/opt/wo/lib/python3.11/site-packages/cement/ext/ext_plugin.py", line 290, in load_plugins
    self.load_plugin(plugin_name)
  File "/opt/wo/lib/python3.11/site-packages/cement/ext/ext_plugin.py", line 259, in load_plugin
    if self._load_plugin_from_bootstrap(plugin_name, self.bootstrap):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/cement/ext/ext_plugin.py", line 225, in _load_plugin_from_bootstrap
    __import__(full_module, globals(), locals(), [], 0)
  File "/opt/wo/lib/python3.11/site-packages/wo/cli/plugins/clean.py", line 8, in <module>
    from wo.core.aptget import WOAptGet
  File "/opt/wo/lib/python3.11/site-packages/wo/core/aptget.py", line 8, in <module>
    import apt
  File "/opt/wo/lib/python3.11/site-packages/apt/__init__.py", line 26, in <module>
    from apt.package import Package
  File "/opt/wo/lib/python3.11/site-packages/apt/package.py", line 41, in <module>
    from collections import Mapping, Sequence
ImportError: cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.11/collections/__init__.py)
WordOps (wo) upgrade to v3.16.3 was succesfull!
Changelog is available on https://github.com/WordOps/WordOps/releases/tag/v3.16.3

To upgrade WordOps web stacks, you can use the command:
wo stack upgrade

To update all other packages, you can use the command:
wo maintenance

WordOps Documentation : https://docs.wordops.net
WordOps Community Forum : https://community.wordops.net
WordOps Community Chat : https://chat.wordops.net

- [ ] `lsb_release -a`
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

- [ ] `wo info`
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/wo/cli/main.py", line 93, in main
    with app:
  File "/opt/wo/lib/python3.11/site-packages/cement/core/foundation.py", line 1501, in __enter__
    self.setup()
  File "/opt/wo/lib/python3.11/site-packages/cement/core/foundation.py", line 852, in setup
    self._setup_plugin_handler()
  File "/opt/wo/lib/python3.11/site-packages/cement/core/foundation.py", line 1339, in _setup_plugin_handler
    self.plugin.load_plugins(self.plugin.get_enabled_plugins())
  File "/opt/wo/lib/python3.11/site-packages/cement/ext/ext_plugin.py", line 290, in load_plugins
    self.load_plugin(plugin_name)
  File "/opt/wo/lib/python3.11/site-packages/cement/ext/ext_plugin.py", line 259, in load_plugin
    if self._load_plugin_from_bootstrap(plugin_name, self.bootstrap):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/cement/ext/ext_plugin.py", line 225, in _load_plugin_from_bootstrap
    __import__(full_module, globals(), locals(), [], 0)
  File "/opt/wo/lib/python3.11/site-packages/wo/cli/plugins/clean.py", line 8, in <module>
    from wo.core.aptget import WOAptGet
  File "/opt/wo/lib/python3.11/site-packages/wo/core/aptget.py", line 8, in <module>
    import apt
  File "/opt/wo/lib/python3.11/site-packages/apt/__init__.py", line 26, in <module>
    from apt.package import Package
  File "/opt/wo/lib/python3.11/site-packages/apt/package.py", line 41, in <module>
    from collections import Mapping, Sequence
ImportError: cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.11/collections/__init__.py)

- [ ] `nginx -V`
nginx version: nginx/1.14.0 (EasyEngine)
built with OpenSSL 1.0.2g-fips  1 Mar 2016 (running with OpenSSL 1.0.2n  7 Dec 2017)
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_v2_module --with-http_sub_module --with-http_xslt_module --add-module=/usr/src/packages/BUILD/debian/modules/headers-more-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/nginx-auth-pam --add-module=/usr/src/packages/BUILD/debian/modules/nginx-cache-purge --add-module=/usr/src/packages/BUILD/debian/modules/nginx-echo --add-module=/usr/src/packages/BUILD/debian/modules/ngx-fancyindex --add-module=/usr/src/packages/BUILD/debian/modules/nginx-lua --add-module=/usr/src/packages/BUILD/debian/modules/nginx-upload-progress --add-module=/usr/src/packages/BUILD/debian/modules/nginx-upstream-fair --add-module=/usr/src/packages/BUILD/debian/modules/ngx_http_substitutions_filter_module --add-module=/usr/src/packages/BUILD/debian/modules/memc-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/srcache-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/HttpRedisModule --add-module=/usr/src/packages/BUILD/debian/modules/redis2-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/ngx_devel_kit --add-module=/usr/src/packages/BUILD/debian/modules/set-misc-nginx-module

- [ ] `wo -v`
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/wo/cli/main.py", line 93, in main
    with app:
  File "/opt/wo/lib/python3.11/site-packages/cement/core/foundation.py", line 1501, in __enter__
    self.setup()
  File "/opt/wo/lib/python3.11/site-packages/cement/core/foundation.py", line 852, in setup
    self._setup_plugin_handler()
  File "/opt/wo/lib/python3.11/site-packages/cement/core/foundation.py", line 1339, in _setup_plugin_handler
    self.plugin.load_plugins(self.plugin.get_enabled_plugins())
  File "/opt/wo/lib/python3.11/site-packages/cement/ext/ext_plugin.py", line 290, in load_plugins
    self.load_plugin(plugin_name)
  File "/opt/wo/lib/python3.11/site-packages/cement/ext/ext_plugin.py", line 259, in load_plugin
    if self._load_plugin_from_bootstrap(plugin_name, self.bootstrap):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/cement/ext/ext_plugin.py", line 225, in _load_plugin_from_bootstrap
    __import__(full_module, globals(), locals(), [], 0)
  File "/opt/wo/lib/python3.11/site-packages/wo/cli/plugins/clean.py", line 8, in <module>
    from wo.core.aptget import WOAptGet
  File "/opt/wo/lib/python3.11/site-packages/wo/core/aptget.py", line 8, in <module>
    import apt
  File "/opt/wo/lib/python3.11/site-packages/apt/__init__.py", line 26, in <module>
    from apt.package import Package
  File "/opt/wo/lib/python3.11/site-packages/apt/package.py", line 41, in <module>
    from collections import Mapping, Sequence
ImportError: cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.11/collections/__init__.py)

**Comment by vincenzocasu** [comment]
I did another upgrade and went to version 20.04 LTS

So I ran the command: ` sudo rm -f /usr/local/bin/wo && wget -qO wo wops.cc && sudo bash wo`

to reinstall WordOps, and now I get this error:

`Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/wo/cli/main.py", line 93, in main
    with app:
  File "/opt/wo/lib/python3.11/site-packages/cement/core/foundation.py", line 1501, in __enter__
    self.setup()
  File "/opt/wo/lib/python3.11/site-packages/cement/core/foundation.py", line 852, in setup
    self._setup_plugin_handler()
  File "/opt/wo/lib/python3.11/site-packages/cement/core/foundation.py", line 1339, in _setup_plugin_handler
    self.plugin.load_plugins(self.plugin.get_enabled_plugins())
  File "/opt/wo/lib/python3.11/site-packages/cement/ext/ext_plugin.py", line 290, in load_plugins
    self.load_plugin(plugin_name)
  File "/opt/wo/lib/python3.11/site-packages/cement/ext/ext_plugin.py", line 259, in load_plugin
    if self._load_plugin_from_bootstrap(plugin_name, self.bootstrap):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/cement/ext/ext_plugin.py", line 225, in _load_plugin_from_bootstrap
    __import__(full_module, globals(), locals(), [], 0)
  File "/opt/wo/lib/python3.11/site-packages/wo/cli/plugins/clean.py", line 8, in <module>
    from wo.core.aptget import WOAptGet
  File "/opt/wo/lib/python3.11/site-packages/wo/core/aptget.py", line 8, in <module>
    import apt
  File "/opt/wo/lib/python3.11/site-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ImportError: libapt-pkg.so.5.0: cannot open shared object file: No such file or directory`



- [ ] `lsb_release -a`
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

- [ ] `nginx -V`
nginx version: nginx/1.18.0 (Ubuntu)
built with OpenSSL 1.1.1f  31 Mar 2020 (running with OpenSSL 1.1.1  11 Sep 2018)
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-lUTckl/nginx-1.18.0=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-compat --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_sub_module --with-http_xslt_module=dynamic --with-stream=dynamic --with-stream_ssl_module --with-mail=dynamic --with-mail_ssl_module

- [ ] `wo info`
`Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/wo/cli/main.py", line 93, in main
    with app:
  File "/opt/wo/lib/python3.11/site-packages/cement/core/foundation.py", line 1501, in __enter__
    self.setup()
  File "/opt/wo/lib/python3.11/site-packages/cement/core/foundation.py", line 852, in setup
    self._setup_plugin_handler()
  File "/opt/wo/lib/python3.11/site-packages/cement/core/foundation.py", line 1339, in _setup_plugin_handler
    self.plugin.load_plugins(self.plugin.get_enabled_plugins())
  File "/opt/wo/lib/python3.11/site-packages/cement/ext/ext_plugin.py", line 290, in load_plugins
    self.load_plugin(plugin_name)
  File "/opt/wo/lib/python3.11/site-packages/cement/ext/ext_plugin.py", line 259, in load_plugin
    if self._load_plugin_from_bootstrap(plugin_name, self.bootstrap):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/cement/ext/ext_plugin.py", line 225, in _load_plugin_from_bootstrap
    __import__(full_module, globals(), locals(), [], 0)
  File "/opt/wo/lib/python3.11/site-packages/wo/cli/plugins/clean.py", line 8, in <module>
    from wo.core.aptget import WOAptGet
  File "/opt/wo/lib/python3.11/site-packages/wo/core/aptget.py", line 8, in <module>
    import apt
  File "/opt/wo/lib/python3.11/site-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ImportError: libapt-pkg.so.5.0: cannot open shared object file: No such file or directory`


Do you have any suggestions for me?

**Comment by vincenzocasu** [comment]
Hello, news about this?

**Comment by VirtuBox** [comment]
Hello @vincenzocasu,
it's pretty hard to tell you what is the issue because you are running pretty outdated Ubuntu releases and there are probably unknown issues with  those old Ubuntu releases. I will try to take a look on this but as a workaround, I suggest you to create a new server with Ubuntu 22.04 LTS and to migrate all your sites on it. I will update the current migration guide : https://docs.wordops.net/guides/wordpress-migration/
