### ISSUE TITLE
Install stack without Database

### ISSUE THREAD

**Issue by MichalisDBA** [WordOps/WordOps#574]
Hello.

Any way to install a complete LE(M)P stack BUT without any MySQL / MariaDB Database.

We have a remote DB server.

**Comment by VirtuBox** [comment]
Hello @MichalisDBA,

here a guide : https://docs.wordops.net/how-to/remote-mysql-server/

**Comment by MichalisDBA** [comment]
> Hello @MichalisDBA,
> 
> here a guide : https://docs.wordops.net/how-to/remote-mysql-server/

Tried to install with

`wo stack install --security --nginx --php81 --utils --redis --composer --netdata --dashboard --sendmail --mysqlclient --extplorer --nanorc --cheat`

but the fllowing error occured

```
Traceback (most recent call last):
  File "/opt/wo/lib/python3.11/site-packages/pymysql/connections.py", line 644, in connect
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/wo/cli/main.py", line 102, in main
    app.run()
  File "/opt/wo/lib/python3.11/site-packages/cement/core/foundation.py", line 882, in run
    return_val = self.controller._dispatch()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
           ^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/cement/core/controller.py", line 477, in _dispatch
    return func()
           ^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/wo/cli/plugins/stack.py", line 522, in install
    post_pref(self, [], packages)
  File "/opt/wo/lib/python3.11/site-packages/wo/cli/plugins/stack_pref.py", line 1337, in post_pref
    WOMysql.execute(self, 'grant select on'
  File "/opt/wo/lib/python3.11/site-packages/wo/core/mysql.py", line 71, in execute
    connection = WOMysql.connect(self)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/wo/core/mysql.py", line 37, in connect
    connection = pymysql.connect(read_default_file='~/.my.cnf')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/wo/lib/python3.11/site-packages/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/opt/wo/lib/python3.11/site-packages/pymysql/connections.py", line 711, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
```

**Comment by MichalisDBA** [comment]
I found the solution.

`--utils` flag tries to install Anemometer `https://github.com/box/Anemometer/archive/master.tar.gz`

I deleted it from `stack.py`

Please remove `Anemometer` package compeletely, the project is abandoned and has SQL injection vulnerability

https://github.com/box/Anemometer/issues/210
