### ISSUE TITLE
Installation script is broken

### ISSUE THREAD

**Issue by sbusso** [WordOps/WordOps#62]
On a fresh server with ubuntu 18.04, email input is not even asked:

```
curl -sL wops.cc | sudo bash

Welcome to WordOps install script v3.9.4.5

Updating apt-get repository info
Installing wo dependencies
Installing WordOps
WordOps (wo) require an username & and an email address to configure Git (used to save server configurations)
Your informations will ONLY be stored locally
Enter your name: Unfortunately, this can't be left blank
Enter your name: Enter your email: Whoops, seems like you made a typo - the e-mailaddress is invalid...
Enter your email: Whoops, seems like you made a typo - the e-mailaddress is invalid...
Enter your email: Whoops, seems like you made a typo - the e-mailaddress is invalid...
Enter your email: Whoops, seems like you made a typo - the e-mailaddress is invalid...
Enter your email: Whoops, seems like you made a typo - the e-mailaddress is invalid...
Enter your email: Whoops, seems like you made a typo - the e-mailaddress is invalid...
Enter your email: Whoops, seems like you made a typo - the e-mailaddress is invalid...
Enter your email: Whoops, seems like you made a typo - the e-mailaddress is invalid...
Enter your email: Whoops, seems like you made a typo - the e-mailaddress is invalid...
Enter your email: Whoops, seems like you made a typo - the e-mailaddress is invalid...
Enter your email: Whoops, seems like you made a typo - the e-mailaddress is invalid...
Enter your email: Whoops, seems like you made a typo - the e-mailaddress is invalid...
Enter your email: Whoops, seems like you made a typo - the e-mailaddress is invalid...
Enter your email: Whoops, seems like you made a typo - the e-mailaddress is invalid...
Enter your email: Whoops, seems like you made a typo - the e-mailaddress is invalid...
Enter your email: Whoops, seems like you made a typo - the e-mailaddress is invalid...
Enter your email: Whoops, seems like you made a typo - the e-mailaddress is invalid...
Enter your email: Traceback (most recent call last):
  File "setup.py", line 33, in <module>
    wo_user = config['user']['name']
  File "/usr/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 50, in <module>
    wo_email = input("Enter your email: ")
EOFError: EOF when reading a line
Installing acme.sh
Running post-install steps
```

**Comment by VirtuBox** [comment]
Hello,
this is an issue due to my tests with alternative install commands for WordOps. 
Please use the previous and working install command : 
```bash
wget -qO wo wops.cc && sudo bash wo
```
I have already updated the repository README.

**Comment by sbusso** [comment]
ok thank you, worked.
