### ISSUE TITLE
Run "wo log show site.com" get error "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 2326: invalid start byte"

### ISSUE THREAD

**Issue by luutan04** [WordOps/WordOps#680]
**Describe the bug**
Run "wo log show site.com" command, I get error UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 2326: invalid start byte

`Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/main.py", line 102, in main
    app.run()
  File "/opt/wo/lib/python3.10/site-packages/cement/core/foundation.py", line 882, in run
    return_val = self.controller._dispatch()
  File "/opt/wo/lib/python3.10/site-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/opt/wo/lib/python3.10/site-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/opt/wo/lib/python3.10/site-packages/cement/core/controller.py", line 477, in _dispatch
    return func()
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/plugins/log.py", line 157, in default
    logwatch(self, watch_list)
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/plugins/site_functions.py", line 1067, in logwatch
    logl.loop()
  File "/opt/wo/lib/python3.10/site-packages/wo/core/logwatch.py", line 75, in loop
    self.readfile(file)
  File "/opt/wo/lib/python3.10/site-packages/wo/core/logwatch.py", line 164, in readfile
    lines = file.readlines()
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 2326: invalid start byte
`

**System information:**
WordOps 3.21.3
Ubuntu 22.04

**Comment by janiosarmento** [comment]
I'm curious: does your domain name contain non-ASCII characters (Punycode)?

**Comment by luutan04** [comment]
> I'm curious: does your domain name contain non-ASCII characters (Punycode)?

No, my domain only contains alphabets similar to abc.com
