### ISSUE TITLE
After purging php8.1, it continues to try to be loaded

### ISSUE THREAD

**Issue by dingman** [WordOps/WordOps#684]
After running

```wo stack purge --php81```

I continue to see php81 trying to be added back

```
# wo stack restart
PHP7.4-FPM is not installed
PHP8.0-FPM is not installed
PHP8.1-FPM is not installed
PHP8.2-FPM is not installed
PHP8.3-FPM is not installed
Testing Nginx configuration     [OK]
Restarting Nginx                [OK]
Restarting php8.1-fpm           [KO]
Restarting php8.3-fpm           [OK]
Restarting mariadb              [OK]
Restarting netdata              [OK]
...
Unable to copy file from /etc/php/8.1/fpm/php.ini to /etc/php/8.1/fpm/php.ini.orig
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/main.py", line 102, in main
    app.run()
  File "/opt/wo/lib/python3.10/site-packages/cement/core/foundation.py", line 882, in run
    return_val = self.controller._dispatch()
  File "/opt/wo/lib/python3.10/site-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/opt/wo/lib/python3.10/site-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/opt/wo/lib/python3.10/site-packages/cement/core/controller.py", line 477, in _dispatch
    return func()
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/plugins/stack_upgrade.py", line 313, in default
    post_pref(self, apt_packages, [], True)
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/plugins/stack_pref.py", line 482, in post_pref
    config['PHP']['expose_php'] = 'Off'
  File "/usr/lib/python3.10/configparser.py", line 965, in __getitem__
    raise KeyError(key)
KeyError: 'PHP'
```

I did the same for netdata and that continues to show back up again

how can I actually purge these from the system via WordOps?

**Comment by dingman** [comment]
@VirtuBox any thoughts?

👀
```
root@ubuntu-s-1vcpu-1gb-sfo3-01:~# wo stack purge --php81
PHP 8.1 already purged
root@ubuntu-s-1vcpu-1gb-sfo3-01:~# wo stack install --php81
PHP 8.1 already installed
root@ubuntu-s-1vcpu-1gb-sfo3-01:~# wo stack purge --php81
PHP 8.1 already purged
```

**Comment by dingman** [comment]
After further triage, I was able to resolve this.

https://askubuntu.com/questions/59886/how-to-completely-remove-php

This solved it:

```
root@ubuntu-s-1vcpu-1gb-sfo3-01:/etc/php# apt-get purge 'php8.1*'
```
