### ISSUE TITLE
Netdata can not purged

### ISSUE THREAD

**Issue by alexlii1971** [WordOps/WordOps#690]
**Describe the bug**

I tried:

 wo stop stack --netdata
wo remove stack --netdata
wo purge stack --netdata

wget -O /tmp/netdata-kickstart.sh https://get.netdata.cloud/kickstart.sh && sh /tmp/netdata-kickstart.sh --uninstall

but, all failed, and netdata is still running when I try TOP:

https://prnt.sc/YLU44g76ZAVK

**System information:**
- [ ] `lsb_release -a`
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

- [ ] `wo info`

wo info

NGINX (1.26.1 ):

user                             www-data
worker_processes                 auto
worker_connections               50000
keepalive_timeout                8
fastcgi_read_timeout             3000
client_max_body_size             100M
allow                            127.0.0.1 ::1 
PHP 8.3 is not installed

PHP (7.4.33):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php74-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9174

PHP (8.0.30):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php80-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9180

PHP (8.1.29):

user                             
expose_php                       Off
memory_limit                     1024M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               3000

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php81-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9181

PHP (8.2.21):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php82-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9182

MySQL (10.6.18-MariaDB) on localhost:

port                             3306
wait_timeout                     60
interactive_timeout              28800
max_used_connections             
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

- [ ] `nginx -V`

ginx -V
nginx version: nginx/1.26.1 (WordOps Nginx-wo)
built with OpenSSL 3.0.2 15 Mar 2022
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -ffile-prefix-map=/build/nginx-9gimZS/nginx-1.26.1=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -fPIC -flto -ffat-lto-objects -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -fPIC -flto -ffat-lto-objects' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo' --with-debug --with-pcre-jit --with-file-aio --with-threads --with-http_ssl_module --with-http_v2_module --with-http_v3_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-openssl-opt='zlib enable-ec_nistp_64_gcc_128 enable-tls1_3 no-ssl3-method -fPIC' --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_sub_module --with-http_xslt_module --without-http_memcached_module --add-module=/build/nginx-9gimZS/nginx-1.26.1/debian/modules/headers-more-nginx-module --add-module=/build/nginx-9gimZS/nginx-1.26.1/debian/modules/nginx-auth-pam --add-module=/build/nginx-9gimZS/nginx-1.26.1/debian/modules/nginx-cache-purge --add-module=/build/nginx-9gimZS/nginx-1.26.1/debian/modules/nginx-echo --add-module=/build/nginx-9gimZS/nginx-1.26.1/debian/modules/nginx-upstream-fair --add-module=/build/nginx-9gimZS/nginx-1.26.1/debian/modules/ngx_http_substitutions_filter_module --add-module=/build/nginx-9gimZS/nginx-1.26.1/debian/modules/memc-nginx-module --add-module=/build/nginx-9gimZS/nginx-1.26.1/debian/modules/srcache-nginx-module --add-module=/build/nginx-9gimZS/nginx-1.26.1/debian/modules/HttpRedisModule --add-module=/build/nginx-9gimZS/nginx-1.26.1/debian/modules/redis2-nginx-module --add-module=/build/nginx-9gimZS/nginx-1.26.1/debian/modules/ngx_devel_kit --add-module=/build/nginx-9gimZS/nginx-1.26.1/debian/modules/set-misc-nginx-module --add-module=/build/nginx-9gimZS/nginx-1.26.1/debian/modules/nginx-module-vts --add-module=/build/nginx-9gimZS/nginx-1.26.1/debian/modules/ngx_brotli

- [ ] `wo -v`

WordOps v3.21.3
Copyright (c) 2024 WordOps.

- [ ] `wp cli info --allow-root`
wp cli info --allow-root
OS:     Linux 5.15.0-107-generic #117-Ubuntu SMP Fri Apr 26 12:26:49 UTC 2024 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php8.2
PHP version:    8.2.21
php.ini used:   /etc/php/8.2/cli/php.ini
MySQL binary:   /usr/bin/mysql
MySQL version:  mysql  Ver 15.1 Distrib 10.6.18-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
SQL modes:      STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /root
WP-CLI packages dir:
WP-CLI cache dir:       /root/.wp-cli/cache
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.10.0

**Additional context**

**Comment by alexlii1971** [comment]
Also, please note that wo debug failed:


` wo debug --all

Setting up Nginx debug connection for 0.0.0.0/0
Enabling PHP debug
Unable to search /etc/php/7.2/mods-available/xdebug.ini and replace ;zend_extension zend_extension
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/main.py", line 102, in main
    app.run()
  File "/opt/wo/lib/python3.10/site-packages/cement/core/foundation.py", line 882, in run
    return_val = self.controller._dispatch()
  File "/opt/wo/lib/python3.10/site-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/opt/wo/lib/python3.10/site-packages/cement/core/controller.py", line 477, in _dispatch
    return func()
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/plugins/debug.py", line 748, in default
    self.debug_php()
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/plugins/debug.py", line 205, in debug_php
    config['debug']['slowlog'] = '/var/log/{0}/slow.log'.format(
  File "/usr/lib/python3.10/configparser.py", line 965, in __getitem__
    raise KeyError(key)
KeyError: 'debug'`

**Comment by Endda** [comment]
Can confirm, netdata is unable to be removed using the documentation provided by the wordops website (and I'd been like this for a while now) 

Many of us are using wordops on an affordable vps and need all of the resources we have available

Netdata just eats up real and CPU cycles and should be uninstalled easily

**Comment by VirtuBox** [comment]
Hello @alexlii1971,
Thanks for your report, I'm working on it.

**Comment by Berttas** [comment]
Wo - the commands worked fine and I just restarted the server and had the netdata out eating up resources.

wget -O /tmp/netdata-kickstart.sh https://get.netdata.cloud/kickstart.sh && sh /tmp/netdata-kickstart.sh --uninstall

wo stack stop --netdata
wo stack remove --netdata
wo stack purge --netdata

The server is:

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04.2 LTS"
