### ISSUE TITLE
UnboundLocalError: local variable 'php_version' referenced before assignment

### ISSUE THREAD

**Issue by arkdev1** [WordOps/WordOps#692]
**Describe the bug**
I've a VPS with 20/22 websites, needed to add a website.

```shell
sudo -E wo site create domain.com --html --letsencrypt=wildcard --dns=dns_cf
```
> Domain redacted for privacy

Output:
```shell
Running pre-update checks       [OK]
Setting up NGINX configuration 	[Done]
Setting up webroot 		[Done]
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/opt/wo/lib/python3.8/site-packages/wo/cli/main.py", line 102, in main
    app.run()
  File "/opt/wo/lib/python3.8/site-packages/cement/core/foundation.py", line 882, in run
    return_val = self.controller._dispatch()
  File "/opt/wo/lib/python3.8/site-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/opt/wo/lib/python3.8/site-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/opt/wo/lib/python3.8/site-packages/cement/core/controller.py", line 477, in _dispatch
    return func()
  File "/opt/wo/lib/python3.8/site-packages/wo/cli/plugins/site_create.py", line 397, in default
    php_version=php_version)
UnboundLocalError: local variable 'php_version' referenced before assignment
```
**System information:**
- [X] `lsb_release -a`
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```

- [X] `wo info`
```

NGINX (1.26.2 ):

user                             www-data
worker_processes                 auto
worker_connections               50000
keepalive_timeout                8
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 ::1 
PHP 8.0 is not installed

PHP (7.4.33):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php74-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9174

PHP (8.1.30):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php81-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9181

PHP (8.2.24):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php82-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9182

PHP (8.3.12):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php83-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9183

MySQL (10.5.26-MariaDB) on localhost:

port                             3306
wait_timeout                     60
interactive_timeout              28800
max_used_connections             
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

```

- [X] `nginx -V`
```
nginx version: nginx/1.26.2 (WordOps Nginx-wo)
built with OpenSSL 1.1.1f  31 Mar 2020
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-IxpI16/nginx-1.26.2=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -flto -ffat-lto-objects -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -fPIC -flto -ffat-lto-objects' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo' --with-debug --with-pcre-jit --with-file-aio --with-threads --with-http_ssl_module --with-http_v2_module --with-http_v3_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-openssl-opt='zlib enable-ec_nistp_64_gcc_128 enable-tls1_3 no-ssl3-method -fPIC' --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_sub_module --with-http_xslt_module --without-http_memcached_module --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/headers-more-nginx-module --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/nginx-auth-pam --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/nginx-cache-purge --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/nginx-echo --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/nginx-upstream-fair --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/ngx_http_substitutions_filter_module --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/memc-nginx-module --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/srcache-nginx-module --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/HttpRedisModule --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/redis2-nginx-module --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/ngx_devel_kit --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/set-misc-nginx-module --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/nginx-module-vts --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/ngx_brotli
```
- [X] `wo -v`
```
WordOps v3.21.3
Copyright (c) 2024 WordOps.
```

**Additional context**
Tried to reinstall wordops with no success, still the error.

**Comment by VirtuBox** [comment]
Hello @arkdev1,
Thanks for your report. A fix will be available soon.

**Comment by arkdev1** [comment]
Hi @VirtuBox, any news? Sorry i've 2 servers now with this problem

**Comment by Siphompeks** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by arkdev1** [comment]
@VirtuBox, the link is a Scam, i'm on Linux so...

**Comment by arkdev1** [comment]
@vikas5914, thanks a lot

**Comment by rajnetgen** [comment]
@VirtuBox any update on this or a fix for now?
Having same issue on a Digitalocean Server.

**Comment by arkdev1** [comment]
> @VirtuBox any update on this or a fix for now? Having same issue on a Digitalocean Server.

Hi @rajnetgen, I’ve found a workaround! If you create a PHP environment, it works. After that, you’ll need to manually update the Nginx configuration. It’s not ideal, but it gets the job done.

My issue only occurs with HTML websites.

**Comment by arkdev1** [comment]
Hi @VirtuBox,
thanks a lot!

**Comment by rajnetgen** [comment]
Still facing same issue with the latest update

![Image](https://github.com/user-attachments/assets/b2f476ef-431d-4b89-94fc-2e731d5afe49)

**Comment by arkdev1** [comment]
> Still facing same issue with the latest update
> 
> ![Image](https://github.com/user-attachments/assets/b2f476ef-431d-4b89-94fc-2e731d5afe49)

Hi @rajnetgen, what command did you use? With WordOps v3.22.0 on Ubuntu 24.04, I have no problems.

**Comment by rajnetgen** [comment]
This error was on  Ubuntu 20.04.6 LTS
Command used 
wo site create domain.tld --wp
wo site create domain.tld --html

Have 3 existing sites but unable to add new ones to the server.

**Comment by luizbills** [comment]
This issue persists in v3.22
