### ISSUE TITLE
WordOps doesn't detect failed LetsEncrypt renewal

### ISSUE THREAD

**Issue by JPaulMora** [WordOps/WordOps#698]
**Describe the bug**
Renewing a cert using Cloudflare:

```bash
Type the appropriate number [1-2] or any other key to cancel: 2
Issuing new SSL cert with acme.sh
2024-10-22 22:26:26,694 (INFO) wo : Issuing new SSL cert with acme.sh
2024-10-22 22:26:26,695 (DEBUG) wo.core.logging : Running command: /etc/letsencrypt/acme.sh --config-home '/etc/letsencrypt/config' --renew -d mail.nimble.gt --ecc --force
2024-10-22 22:26:28,751 (DEBUG) wo.core.logging : Command Output: [Tue Oct 22 22:26:26 MDT 2024] Renewing: 'mail.nimble.gt'
[Tue Oct 22 22:26:26 MDT 2024] Renewing using Le_API=https://acme-v02.api.letsencrypt.org/directory
[Tue Oct 22 22:26:27 MDT 2024] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Tue Oct 22 22:26:27 MDT 2024] Single domain='mail.nimble.gt'
[Tue Oct 22 22:26:27 MDT 2024] Getting webroot for domain='mail.nimble.gt'
[Tue Oct 22 22:26:27 MDT 2024] Adding TXT value: BxJDpJ-hDDr-0SXSog92iX3qMdOGfHPLjSHD-mXk_4A for domain: _acme-challenge.mail.nimble.gt
, 
Command Error: [Tue Oct 22 22:26:28 MDT 2024] invalid domain
[Tue Oct 22 22:26:28 MDT 2024] Error adding TXT record to domain: _acme-challenge.mail.nimble.gt
[Tue Oct 22 22:26:28 MDT 2024] Please add '--debug' or '--log' to see more information.
[Tue Oct 22 22:26:28 MDT 2024] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh

2024-10-22 22:26:28,752 (INFO) wo : Testing Nginx configuration 
Testing Nginx configuration     [OK]
2024-10-22 22:26:28,891 (INFO) wo : Testing Nginx configuration 
2024-10-22 22:26:28,892 (INFO) wo : Reloading Nginx
Reloading Nginx                 [OK]
2024-10-22 22:26:28,910 (INFO) wo : Reloading Nginx
Congratulations! Successfully Configured SSL on https://mail.nimble.gt
2024-10-22 22:26:28,911 (INFO) wo : Congratulations! Successfully Configured SSL on https://mail.nimble.gt
2024-10-22 22:26:28,911 (DEBUG) wo.core.logging : Getting expiration of /etc/letsencrypt/live/mail.nimble.gt/cert.pem
2024-10-22 22:26:28,911 (DEBUG) wo.core.logging : Running command: date -d "now" +%s
2024-10-22 22:26:28,914 (DEBUG) wo.core.logging : Command Output: 1729657588
, 
Command Error: 
2024-10-22 22:26:28,915 (DEBUG) wo.core.logging : Running command: date -d "$(openssl x509 -in /etc/letsencrypt/live/mail.nimble.gt/cert.pem -text -noout | grep "Not After" | cut -c 25-)" +%s
2024-10-22 22:26:28,921 (DEBUG) wo.core.logging : Command Output: 1724374544
, 
Command Error: 
Your cert already EXPIRED ! .PLEASE renew soon . 
2024-10-22 22:26:28,921 (WARNING) wo : Your cert already EXPIRED ! .PLEASE renew soon . 

```

**System information:**
- [x] `lsb_release -a`
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

- [x] `wo info`
```bash
2024-10-22 22:29:18,600 (INFO) wo : Initializing WordOps Database

NGINX (1.26.2 ):

user                             www-data
worker_processes                 auto
worker_connections               50000
keepalive_timeout                8
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 ::1 
PHP 8.2 is not installed
2024-10-22 22:29:21,461 (INFO) wo : PHP 8.2 is not installed
PHP 8.3 is not installed
2024-10-22 22:29:22,012 (INFO) wo : PHP 8.3 is not installed
2024-10-22 22:29:22,017 (DEBUG) wo.core.logging : 'php_admin_flag[xdebug.profiler_enable_trigger]'

PHP (7.4.33):

user                             
expose_php                       Off
memory_limit                     2048M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php74-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9174
2024-10-22 22:29:22,135 (DEBUG) wo.core.logging : 'php_admin_flag[xdebug.profiler_enable_trigger]'

PHP (8.0.30):

user                             
expose_php                       Off
memory_limit                     2048M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               400

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php80-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9180
2024-10-22 22:29:22,200 (DEBUG) wo.core.logging : 'php_admin_flag[xdebug.profiler_enable_trigger]'

PHP (8.1.29):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php81-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9181
2024-10-22 22:29:22,292 (DEBUG) wo.core.logging : Running command: /usr/bin/mariadb-admin ping
2024-10-22 22:29:22,306 (DEBUG) wo.core.logging : Command Output: mysqld is alive
, 
Command Error: 

MySQL (10.5.26-MariaDB) on localhost:

port                             3306
wait_timeout                     60
interactive_timeout              28800
max_used_connections             
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf
```
- [x] `nginx -V`
```bash
nginx version: nginx/1.26.2 (WordOps Nginx-wo)
built with OpenSSL 1.1.1f  31 Mar 2020
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-IxpI16/nginx-1.26.2=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -flto -ffat-lto-objects -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -fPIC -flto -ffat-lto-objects' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo' --with-debug --with-pcre-jit --with-file-aio --with-threads --with-http_ssl_module --with-http_v2_module --with-http_v3_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-openssl-opt='zlib enable-ec_nistp_64_gcc_128 enable-tls1_3 no-ssl3-method -fPIC' --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_sub_module --with-http_xslt_module --without-http_memcached_module --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/headers-more-nginx-module --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/nginx-auth-pam --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/nginx-cache-purge --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/nginx-echo --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/nginx-upstream-fair --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/ngx_http_substitutions_filter_module --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/memc-nginx-module --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/srcache-nginx-module --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/HttpRedisModule --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/redis2-nginx-module --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/ngx_devel_kit --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/set-misc-nginx-module --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/nginx-module-vts --add-module=/build/nginx-IxpI16/nginx-1.26.2/debian/modules/ngx_brotli
```
- [x] `wo -v`
```bash
WordOps v3.21.3
Copyright (c) 2024 WordOps.
Traceback (most recent call last):
  File "/opt/wo/lib/python3.8/site-packages/wo/cli/main.py", line 102, in main
    app.run()
  File "/opt/wo/lib/python3.8/site-packages/cement/core/foundation.py", line 882, in run
    return_val = self.controller._dispatch()
  File "/opt/wo/lib/python3.8/site-packages/cement/core/controller.py", line 474, in _dispatch
    self._parse_args()
  File "/opt/wo/lib/python3.8/site-packages/cement/core/controller.py", line 451, in _parse_args
    self.app._parse_args()
  File "/opt/wo/lib/python3.8/site-packages/cement/core/foundation.py", line 1158, in _parse_args
    self._parsed_args = self.args.parse(self.argv)
  File "/opt/wo/lib/python3.8/site-packages/cement/ext/ext_argparse.py", line 242, in parse
    args = self.parse_args(arg_list)
  File "/usr/lib/python3.8/argparse.py", line 1780, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 1812, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 2018, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.8/argparse.py", line 1958, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.8/argparse.py", line 1886, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.8/argparse.py", line 1083, in __call__
    parser.exit()
  File "/usr/lib/python3.8/argparse.py", line 2520, in exit
    _sys.exit(status)
SystemExit: 0
``
- [x] `wp cli info --allow-root`
```bash
OS:	Linux 5.4.0-170-generic #188-Ubuntu SMP Wed Jan 10 09:51:01 UTC 2024 x86_64
Shell:	/usr/bin/zsh
PHP binary:	/usr/bin/php8.1
PHP version:	8.1.29
php.ini used:	/etc/php/8.1/cli/php.ini
MySQL binary:	/usr/bin/mysql
MySQL version:	mysql  Ver 15.1 Distrib 10.5.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
SQL modes:	STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/root
WP-CLI packages dir:	
WP-CLI cache dir:	/root/.wp-cli/cache
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.11.0
```

**Additional context**

**Comment by Siphompeks** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by VirtuBox** [comment]
Hello @JPaulMora,
thanks for your report, I'm working on it.
